// Dictionnaire des commandes de la HP48G.
// piles : les différentes formes d'arguments, « avant → après », niveau 1 à droite.
// page : page dans le PDF de l'AUG (public/aug.pdf) — à remplir quand le PDF sera dans le repo.

export type Commande = {
  nom: string
  sujet: string
  piles?: string[]
  description: string
  details?: string
  exemple?: string
  page?: number
}

// Lien vers l'AUG. Quand le PDF sera commité dans public/aug.pdf,
// les fiches avec `page` pointeront sur aug.pdf#page=N.
export const AUG_DRIVE =
  'https://drive.google.com/file/d/1BAoSnR6ZLvVrRAKj6_AeyrVOzAdX0v2N/view'

export const SUJETS = [
  'Pile',
  'Maths réels',
  'Complexes',
  'Binaire & bits',
  'Tests & logique',
  'Programmation',
  'Erreurs',
  'Mémoire & variables',
  'Listes',
  'Chaînes',
  'Matrices & vecteurs',
  'Graphismes & GROB',
  'Tracé de courbes',
  'Symbolique',
  'Statistiques',
  'Unités',
  'Heure & date',
  'Affichage & clavier',
] as const

export const COMMANDES: Commande[] = [
  // ── Pile ─────────────────────────────────────────────────────────────
  { nom: 'DUP', sujet: 'Pile', piles: ['obj → obj obj'], description: 'Duplique l’objet du niveau 1.', details: 'ENTER sur une pile non vide fait un DUP implicite.' },
  { nom: 'DUP2', sujet: 'Pile', piles: ['a b → a b a b'], description: 'Duplique les deux premiers niveaux.' },
  { nom: 'DUPN', sujet: 'Pile', piles: ['objₙ…obj₁ n → objₙ…obj₁ objₙ…obj₁'], description: 'Duplique les n premiers niveaux de la pile.' },
  { nom: 'DROP', sujet: 'Pile', piles: ['obj →'], description: 'Supprime l’objet du niveau 1.' },
  { nom: 'DROP2', sujet: 'Pile', piles: ['a b →'], description: 'Supprime les deux premiers niveaux.' },
  { nom: 'DROPN', sujet: 'Pile', piles: ['objₙ…obj₁ n →'], description: 'Supprime les n premiers niveaux.' },
  { nom: 'SWAP', sujet: 'Pile', piles: ['a b → b a'], description: 'Échange les niveaux 1 et 2.', details: 'Touche flèche droite en mode pile interactif.' },
  { nom: 'OVER', sujet: 'Pile', piles: ['a b → a b a'], description: 'Copie le niveau 2 au niveau 1.' },
  { nom: 'ROT', sujet: 'Pile', piles: ['a b c → b c a'], description: 'Fait tourner les trois premiers niveaux : le niveau 3 passe au niveau 1.', details: 'Équivaut à 3 ROLL.' },
  { nom: 'ROLL', sujet: 'Pile', piles: ['objₙ…obj₁ n → objₙ₋₁…obj₁ objₙ'], description: 'Fait remonter le niveau n au niveau 1.' },
  { nom: 'ROLLD', sujet: 'Pile', piles: ['objₙ…obj₁ n → obj₁ objₙ…obj₂'], description: 'Fait descendre le niveau 1 au niveau n (inverse de ROLL).' },
  { nom: 'PICK', sujet: 'Pile', piles: ['objₙ…obj₁ n → objₙ…obj₁ objₙ'], description: 'Copie le niveau n au niveau 1 sans le déplacer.', details: '2 PICK ≡ OVER.' },
  { nom: 'DEPTH', sujet: 'Pile', piles: ['→ n'], description: 'Renvoie le nombre d’objets présents sur la pile.' },
  { nom: 'CLEAR', sujet: 'Pile', piles: ['obj… →'], description: 'Vide entièrement la pile.', details: 'Récupérable juste après avec UNDO (touche EVAL en shift droit).' },
  { nom: 'LASTARG', sujet: 'Pile', piles: ['→ obj…'], description: 'Remet sur la pile les arguments consommés par la dernière commande.', details: 'Désactivable via le drapeau −55 pour économiser la mémoire.' },

  // ── Maths réels ──────────────────────────────────────────────────────
  { nom: '+', sujet: 'Maths réels', piles: ['x y → x+y', '#n₁ #n₂ → #n₃', '[A] [B] → [A+B]', '{ l₁ } { l₂ } → { l₁ l₂ }', '{ } obj → { … obj }', 'obj { } → { obj … }', '"a" "b" → "ab"', 'x_u y_v → z_u'], description: 'Addition — concatène les listes et les chaînes, additionne matrices et unités.', details: 'Sur les unités, convertit le niveau 1 vers l’unité du niveau 2 avant d’additionner.' },
  { nom: '-', sujet: 'Maths réels', piles: ['x y → x−y', '#n₁ #n₂ → #n₃', '[A] [B] → [A−B]', 'x_u y_v → z_u'], description: 'Soustraction.' },
  { nom: '*', sujet: 'Maths réels', piles: ['x y → x·y', '[[A]] [[B]] → [[AB]]', '[[A]] [v] → [Av]', 'x [A] → [xA]', 'x_u y_v → z_uv'], description: 'Multiplication — produit matriciel si les deux niveaux sont des matrices.', details: 'Les dimensions doivent être compatibles pour le produit matriciel.' },
  { nom: '/', sujet: 'Maths réels', piles: ['x y → x/y', '[B] [[A]] → [X] tel que AX=B', 'x_u y_v → z_u/v'], description: 'Division — sur les tableaux, résout le système linéaire AX=B.' },
  { nom: '^', sujet: 'Maths réels', piles: ['x y → xʸ', 'z w → zʷ'], description: 'Puissance.', details: 'Base négative avec exposant non entier → résultat complexe (drapeau −19 selon le mode).' },
  { nom: 'INV', sujet: 'Maths réels', piles: ['x → 1/x', 'z → 1/z', '[[A]] → [[A⁻¹]]'], description: 'Inverse — matrice inverse sur les matrices carrées.' },
  { nom: 'NEG', sujet: 'Maths réels', piles: ['x → −x', 'z → −z', '[A] → [−A]', 'grob → grob inversé'], description: 'Change le signe. Sur un GROB, inverse tous les pixels.' },
  { nom: 'SQ', sujet: 'Maths réels', piles: ['x → x²', 'z → z²', '[[A]] → [[A·A]]'], description: 'Carré.' },
  { nom: '√', sujet: 'Maths réels', piles: ['x → √x', 'z → √z'], description: 'Racine carrée.', details: 'Négatif → erreur ou complexe selon le drapeau −19/−3.' },
  { nom: 'XROOT', sujet: 'Maths réels', piles: ['x n → ⁿ√x'], description: 'Racine n-ième (n au niveau 1).' },
  { nom: 'SIN', sujet: 'Maths réels', piles: ['x → sin x', 'z → sin z', 'symb → symb'], description: 'Sinus.', details: 'Dépend du mode angulaire : DEG, RAD ou GRAD (drapeaux −17/−18).' },
  { nom: 'COS', sujet: 'Maths réels', piles: ['x → cos x', 'z → cos z', 'symb → symb'], description: 'Cosinus.', details: 'Dépend du mode angulaire.' },
  { nom: 'TAN', sujet: 'Maths réels', piles: ['x → tan x', 'z → tan z', 'symb → symb'], description: 'Tangente.', details: 'Dépend du mode angulaire ; infini à 90° en DEG.' },
  { nom: 'ASIN', sujet: 'Maths réels', piles: ['x → arcsin x', 'z → arcsin z'], description: 'Arc sinus.', details: 'Résultat dans le mode angulaire courant ; |x|>1 → complexe.' },
  { nom: 'ACOS', sujet: 'Maths réels', piles: ['x → arccos x', 'z → arccos z'], description: 'Arc cosinus.' },
  { nom: 'ATAN', sujet: 'Maths réels', piles: ['x → arctan x', 'z → arctan z'], description: 'Arc tangente.' },
  { nom: 'EXP', sujet: 'Maths réels', piles: ['x → eˣ', 'z → eᶻ'], description: 'Exponentielle.' },
  { nom: 'LN', sujet: 'Maths réels', piles: ['x → ln x', 'z → ln z'], description: 'Logarithme népérien.', details: 'LN(0) → erreur « Infinite Result » (ou ±∞ si drapeau −22 levé).' },
  { nom: 'LOG', sujet: 'Maths réels', piles: ['x → log₁₀ x', 'z → log z'], description: 'Logarithme décimal.' },
  { nom: 'ALOG', sujet: 'Maths réels', piles: ['x → 10ˣ'], description: 'Antilogarithme : 10 puissance x.' },
  { nom: 'ABS', sujet: 'Maths réels', piles: ['x → |x|', 'z → |z| (module)', '[v] → ‖v‖ (norme)', 'x_u → |x|_u'], description: 'Valeur absolue, module d’un complexe ou norme euclidienne d’un vecteur.' },
  { nom: 'SIGN', sujet: 'Maths réels', piles: ['x → −1 / 0 / 1', 'z → z/|z|'], description: 'Signe d’un réel ; vecteur unitaire pour un complexe.' },
  { nom: 'IP', sujet: 'Maths réels', piles: ['x → int(x)'], description: 'Partie entière (troncature vers zéro).' },
  { nom: 'FP', sujet: 'Maths réels', piles: ['x → frac(x)'], description: 'Partie fractionnaire (même signe que x).' },
  { nom: 'FLOOR', sujet: 'Maths réels', piles: ['x → ⌊x⌋'], description: 'Plus grand entier inférieur ou égal à x.' },
  { nom: 'CEIL', sujet: 'Maths réels', piles: ['x → ⌈x⌉'], description: 'Plus petit entier supérieur ou égal à x.' },
  { nom: 'RND', sujet: 'Maths réels', piles: ['x n → x arrondi', 'x → x arrondi (format courant)'], description: 'Arrondit à n décimales (0–11), ou selon le format d’affichage courant.' },
  { nom: 'TRNC', sujet: 'Maths réels', piles: ['x n → x tronqué'], description: 'Tronque à n décimales sans arrondir.' },
  { nom: 'MOD', sujet: 'Maths réels', piles: ['a b → a mod b'], description: 'Reste de la division ; le résultat a le signe de b.', details: '−3 2 MOD → 1 (pas −1).' },
  { nom: 'MAX', sujet: 'Maths réels', piles: ['a b → max(a,b)'], description: 'Le plus grand des deux nombres.' },
  { nom: 'MIN', sujet: 'Maths réels', piles: ['a b → min(a,b)'], description: 'Le plus petit des deux nombres.' },
  { nom: '%', sujet: 'Maths réels', piles: ['a b → a·b/100'], description: 'b pourcent de a.', details: '200 15 % → 30.' },
  { nom: '%CH', sujet: 'Maths réels', piles: ['a b → 100·(b−a)/a'], description: 'Variation en pourcentage pour passer de a à b.' },
  { nom: '%T', sujet: 'Maths réels', piles: ['a b → 100·b/a'], description: 'Pourcentage que représente b par rapport à a.' },
  { nom: 'RAND', sujet: 'Maths réels', piles: ['→ x'], description: 'Nombre pseudo-aléatoire dans [0,1).', details: 'Suite déterministe ; initialiser avec RDZ.' },
  { nom: 'RDZ', sujet: 'Maths réels', piles: ['x →'], description: 'Initialise la graine du générateur aléatoire.', details: '0 RDZ prend l’horloge comme graine.' },
  { nom: '!', sujet: 'Maths réels', piles: ['n → n!', 'x → Γ(x+1)'], description: 'Factorielle ; fonction gamma pour les non-entiers.', details: 'Maximum : 253.' },
  { nom: 'COMB', sujet: 'Maths réels', piles: ['n k → C(n,k)'], description: 'Nombre de combinaisons de n objets pris k à k.' },
  { nom: 'PERM', sujet: 'Maths réels', piles: ['n k → P(n,k)'], description: 'Nombre de permutations (arrangements) de n objets pris k à k.' },
  { nom: 'MANT', sujet: 'Maths réels', piles: ['x → mantisse'], description: 'Mantisse : 1234.5 MANT → 1.2345.' },
  { nom: 'XPON', sujet: 'Maths réels', piles: ['x → exposant'], description: 'Exposant décimal : 1234.5 XPON → 3.' },
  { nom: '→NUM', sujet: 'Maths réels', piles: ['symb → x'], description: 'Évalue numériquement une expression symbolique.', details: 'Équivaut à EVAL avec le drapeau −3 (mode numérique) forcé.' },
  { nom: 'PI', sujet: 'Maths réels', piles: ['→ π'], description: 'La constante π.', details: 'Reste symbolique tant que le drapeau −3 (numérique) n’est pas levé ; →NUM pour 3.14159265359.' },

  // ── Complexes ────────────────────────────────────────────────────────
  { nom: 'RE', sujet: 'Complexes', piles: ['(x,y) → x', 'x → x', '[C] → [re]'], description: 'Partie réelle.' },
  { nom: 'IM', sujet: 'Complexes', piles: ['(x,y) → y', 'x → 0', '[C] → [im]'], description: 'Partie imaginaire.' },
  { nom: 'ARG', sujet: 'Complexes', piles: ['(x,y) → θ'], description: 'Argument (angle polaire) du complexe, dans le mode angulaire courant.' },
  { nom: 'CONJ', sujet: 'Complexes', piles: ['(x,y) → (x,−y)', '[C] → [C̄]'], description: 'Conjugué complexe.' },
  { nom: 'R→C', sujet: 'Complexes', piles: ['x y → (x,y)', '[X] [Y] → [C]'], description: 'Combine deux réels (ou deux tableaux réels) en complexe(s).' },
  { nom: 'C→R', sujet: 'Complexes', piles: ['(x,y) → x y', '[C] → [X] [Y]'], description: 'Sépare un complexe en partie réelle et imaginaire.' },

  // ── Binaire & bits ───────────────────────────────────────────────────
  { nom: 'BIN', sujet: 'Binaire & bits', description: 'Passe en base binaire pour l’affichage et la saisie des entiers #.', details: 'Suffixe b : #1010b. Drapeaux −11/−12.' },
  { nom: 'DEC', sujet: 'Binaire & bits', description: 'Passe en base décimale pour les entiers #.', details: 'Suffixe d : #10d.' },
  { nom: 'HEX', sujet: 'Binaire & bits', description: 'Passe en base hexadécimale pour les entiers #.', details: 'Suffixe h : #Ah.' },
  { nom: 'OCT', sujet: 'Binaire & bits', description: 'Passe en base octale pour les entiers #.', details: 'Suffixe o : #12o.' },
  { nom: 'STWS', sujet: 'Binaire & bits', piles: ['n →'], description: 'Fixe la taille de mot des entiers binaires (1 à 64 bits).', details: 'Les opérations tronquent au nombre de bits choisi.' },
  { nom: 'RCWS', sujet: 'Binaire & bits', piles: ['→ n'], description: 'Renvoie la taille de mot courante.' },
  { nom: 'R→B', sujet: 'Binaire & bits', piles: ['x → #n'], description: 'Convertit un réel en entier binaire.', details: 'Arrondi à l’entier ; négatif → 0.' },
  { nom: 'B→R', sujet: 'Binaire & bits', piles: ['#n → x'], description: 'Convertit un entier binaire en réel.' },
  { nom: 'SL', sujet: 'Binaire & bits', piles: ['#n → #n·2'], description: 'Décale tous les bits d’un cran vers la gauche.' },
  { nom: 'SR', sujet: 'Binaire & bits', piles: ['#n → #n/2'], description: 'Décale tous les bits d’un cran vers la droite.' },
  { nom: 'ASR', sujet: 'Binaire & bits', piles: ['#n → #n'], description: 'Décalage arithmétique à droite : le bit de poids fort est conservé.' },
  { nom: 'RL', sujet: 'Binaire & bits', piles: ['#n → #n'], description: 'Rotation d’un bit vers la gauche (le bit sortant revient à droite).' },
  { nom: 'RR', sujet: 'Binaire & bits', piles: ['#n → #n'], description: 'Rotation d’un bit vers la droite.' },
  { nom: 'SLB', sujet: 'Binaire & bits', piles: ['#n → #n·256'], description: 'Décalage d’un octet (8 bits) vers la gauche.' },
  { nom: 'SRB', sujet: 'Binaire & bits', piles: ['#n → #n/256'], description: 'Décalage d’un octet vers la droite.' },

  // ── Tests & logique ──────────────────────────────────────────────────
  { nom: '==', sujet: 'Tests & logique', piles: ['a b → 0/1', 'symb obj → symb'], description: 'Test d’égalité (numérique et par valeur).', details: 'Avec un symbolique, construit une équation ; à ne pas confondre avec = (définition).' },
  { nom: '≠', sujet: 'Tests & logique', piles: ['a b → 0/1'], description: 'Test de différence.' },
  { nom: '<', sujet: 'Tests & logique', piles: ['x y → 0/1', '"a" "b" → 0/1'], description: 'Strictement inférieur ; ordre lexicographique sur les chaînes.' },
  { nom: '>', sujet: 'Tests & logique', piles: ['x y → 0/1', '"a" "b" → 0/1'], description: 'Strictement supérieur.' },
  { nom: '≤', sujet: 'Tests & logique', piles: ['x y → 0/1'], description: 'Inférieur ou égal.' },
  { nom: '≥', sujet: 'Tests & logique', piles: ['x y → 0/1'], description: 'Supérieur ou égal.' },
  { nom: 'SAME', sujet: 'Tests & logique', piles: ['obj obj → 0/1'], description: 'Vrai si les deux objets sont rigoureusement identiques.', details: 'Contrairement à ==, ne fait aucune évaluation numérique.' },
  { nom: 'AND', sujet: 'Tests & logique', piles: ['x y → 0/1', '#a #b → #a∧b', '"s1" "s2" → "s"'], description: 'ET logique ; bit à bit sur les entiers binaires.' },
  { nom: 'OR', sujet: 'Tests & logique', piles: ['x y → 0/1', '#a #b → #a∨b'], description: 'OU logique ; bit à bit sur les #.' },
  { nom: 'XOR', sujet: 'Tests & logique', piles: ['x y → 0/1', '#a #b → #a⊕b'], description: 'OU exclusif logique ou bit à bit.' },
  { nom: 'NOT', sujet: 'Tests & logique', piles: ['x → 0/1', '#a → #ā'], description: 'Négation logique ; complément à un sur les #.' },
  { nom: 'IFT', sujet: 'Tests & logique', piles: ['test obj →'], description: 'Si test est vrai (≠0), évalue l’objet ; sinon le jette.' },
  { nom: 'IFTE', sujet: 'Tests & logique', piles: ['test vrai faux →', 'IFTE(test,vrai,faux) en algébrique'], description: 'Si test vrai, évalue le premier objet, sinon le second.', details: 'Utilisable dans une expression algébrique.' },
  { nom: 'TYPE', sujet: 'Tests & logique', piles: ['obj → n'], description: 'Numéro de type de l’objet.', details: '0 réel, 1 complexe, 2 chaîne, 3/4 tableau, 5 liste, 6 nom global, 8 programme, 9 algébrique, 10 #, 11 GROB, 15 répertoire…' },
  { nom: 'SF', sujet: 'Tests & logique', piles: ['n →'], description: 'Lève le drapeau n.', details: 'n de 1 à 64 : drapeaux utilisateur ; n négatif : drapeaux système.' },
  { nom: 'CF', sujet: 'Tests & logique', piles: ['n →'], description: 'Baisse le drapeau n.' },
  { nom: 'FS?', sujet: 'Tests & logique', piles: ['n → 0/1'], description: 'Vrai si le drapeau n est levé.' },
  { nom: 'FC?', sujet: 'Tests & logique', piles: ['n → 0/1'], description: 'Vrai si le drapeau n est baissé.' },
  { nom: 'FS?C', sujet: 'Tests & logique', piles: ['n → 0/1'], description: 'Teste si le drapeau est levé, puis le baisse.' },
  { nom: 'FC?C', sujet: 'Tests & logique', piles: ['n → 0/1'], description: 'Teste si le drapeau est baissé, puis le baisse.' },

  // ── Programmation ────────────────────────────────────────────────────
  { nom: 'IF…THEN…END', sujet: 'Programmation', piles: ['IF test THEN actions END'], description: 'Conditionnelle : exécute les actions si le test est vrai (≠0).', details: 'Le test peut aussi être posé sur la pile avant le IF.', exemple: '« IF X 0 < THEN "négatif" MSGBOX END »' },
  { nom: 'IF…THEN…ELSE…END', sujet: 'Programmation', piles: ['IF test THEN si-vrai ELSE si-faux END'], description: 'Conditionnelle complète avec branche sinon.', exemple: '« IF X 2 MOD THEN "impair" ELSE "pair" END MSGBOX »' },
  { nom: 'IF', sujet: 'Programmation', description: 'Ouvre une conditionnelle. Tout ce qui est entre IF et THEN constitue le test.', details: 'Voir IF…THEN…END et IF…THEN…ELSE…END.' },
  { nom: 'THEN', sujet: 'Programmation', description: 'Sépare le test des actions dans IF et CASE ; consomme le résultat du test (vrai = ≠0).', details: 'Utilisé dans IF…THEN…END, CASE…END et IFERR…THEN…END.' },
  { nom: 'ELSE', sujet: 'Programmation', description: 'Introduit la branche exécutée quand le test est faux.', details: 'Valide dans IF…THEN…ELSE…END et IFERR…THEN…ELSE…END.' },
  { nom: 'END', sujet: 'Programmation', description: 'Termine une structure : IF, CASE (chaque branche et le bloc), WHILE…REPEAT, DO…UNTIL, IFERR.', details: 'Chaque structure ouverte doit avoir son END — l’éditeur les insère par paires.' },
  { nom: 'CASE…END', sujet: 'Programmation', piles: ['CASE t₁ THEN a₁ END t₂ THEN a₂ END … défaut END'], description: 'Choix multiple : exécute la première branche dont le test est vrai, puis saute à la fin.', details: 'Les actions par défaut (optionnelles) se placent juste avant le dernier END.', exemple: '« CASE X 0 < THEN "nég" END X 0 == THEN "nul" END "pos" END »' },
  { nom: 'CASE', sujet: 'Programmation', description: 'Ouvre un choix multiple ; chaque branche est test THEN actions END.', details: 'Voir CASE…END.' },
  { nom: 'FOR…NEXT', sujet: 'Programmation', piles: ['début fin FOR i actions NEXT'], description: 'Boucle avec compteur : i est une variable locale visible dans le corps.', details: 'Le compteur va de début à fin inclus, pas de 1. Le corps s’exécute au moins une fois.', exemple: '« 1 5 FOR i i SQ NEXT »  → 1 4 9 16 25' },
  { nom: 'FOR…STEP', sujet: 'Programmation', piles: ['début fin FOR i actions pas STEP'], description: 'Comme FOR…NEXT mais le pas est fourni avant STEP (négatif ou fractionnaire permis).', exemple: '« 10 2 FOR i i -2 STEP »  → 10 8 6 4 2' },
  { nom: 'FOR', sujet: 'Programmation', piles: ['début fin FOR nom'], description: 'Ouvre une boucle à compteur : consomme les bornes et crée la variable locale nommée.', details: 'Se termine par NEXT (pas de 1) ou pas STEP.' },
  { nom: 'NEXT', sujet: 'Programmation', description: 'Ferme une boucle FOR ou START : incrémente de 1 et reboucle tant que le compteur ≤ fin.', },
  { nom: 'STEP', sujet: 'Programmation', piles: ['pas STEP'], description: 'Ferme une boucle FOR ou START avec un pas explicite pris sur la pile.', details: 'Pas négatif : la boucle descend et s’arrête quand le compteur < fin.' },
  { nom: 'START…NEXT', sujet: 'Programmation', piles: ['début fin START actions NEXT'], description: 'Boucle simple sans variable de compteur.', exemple: '« 1 4 START "ha" NEXT »  → "ha" "ha" "ha" "ha"' },
  { nom: 'START', sujet: 'Programmation', piles: ['début fin START'], description: 'Ouvre une boucle comptée sans variable ; se ferme par NEXT ou STEP.' },
  { nom: 'WHILE…REPEAT…END', sujet: 'Programmation', piles: ['WHILE test REPEAT actions END'], description: 'Boucle tant que : le test est évalué avant chaque itération ; zéro passage possible.', exemple: '« WHILE X 100 < REPEAT X 2 * \'X\' STO END »' },
  { nom: 'WHILE', sujet: 'Programmation', description: 'Ouvre une boucle « tant que » ; le test se place entre WHILE et REPEAT.' },
  { nom: 'REPEAT', sujet: 'Programmation', description: 'Consomme le test d’un WHILE : si vrai exécute le corps puis reboucle, si faux sort au END.' },
  { nom: 'DO…UNTIL…END', sujet: 'Programmation', piles: ['DO actions UNTIL test END'], description: 'Boucle jusqu’à : exécute le corps au moins une fois, s’arrête quand le test devient vrai.', exemple: '« DO RAND UNTIL DUP .9 > END »' },
  { nom: 'DO', sujet: 'Programmation', description: 'Ouvre une boucle « jusqu’à » ; le corps va de DO à UNTIL.' },
  { nom: 'UNTIL', sujet: 'Programmation', description: 'Sépare le corps du test dans DO…UNTIL…END ; le test va de UNTIL à END.', details: 'La boucle s’arrête quand le test est vrai (≠0).' },
  { nom: '→', sujet: 'Programmation', piles: ['obj… → (lie aux noms locaux)', '→ a b « corps »', '→ a b \'expr\''], description: 'Variables locales : prend les objets de la pile et les lie aux noms, visibles dans le programme ou l’expression qui suit.' },
  { nom: 'EVAL', sujet: 'Programmation', piles: ['obj →  (résultat selon l’objet)'], description: 'Évalue l’objet : exécute un programme, rappelle un nom, calcule une expression, éclate une liste.' },
  { nom: 'HALT', sujet: 'Programmation', description: 'Suspend le programme et rend la main à l’utilisateur.', details: 'Reprise avec CONT ; l’annonciateur HLT s’affiche.' },
  { nom: 'CONT', sujet: 'Programmation', description: 'Reprend un programme suspendu par HALT ou PROMPT.' },
  { nom: 'KILL', sujet: 'Programmation', description: 'Abandonne tous les programmes suspendus.' },
  { nom: 'WAIT', sujet: 'Programmation', piles: ['x →', '0 → n (code touche)', '−1 → n (affiche le menu)'], description: 'Pause de x secondes. Avec 0 ou −1, attend une touche et renvoie son code rc.p (ligne, colonne, plan).', details: 'Ex. : 91.1 = touche ENTER.' },
  { nom: 'RCLF', sujet: 'Programmation', piles: ['→ { #système #utilisateur }'], description: 'Sauvegarde l’état de tous les drapeaux dans une liste.' },
  { nom: 'STOF', sujet: 'Programmation', piles: ['{ #s #u } →', '#s →'], description: 'Restaure l’état des drapeaux depuis RCLF.' },
  { nom: 'MEM', sujet: 'Programmation', piles: ['→ n'], description: 'Mémoire libre en octets.', details: 'Déclenche un ramasse-miettes avant la mesure.' },
  { nom: 'BYTES', sujet: 'Programmation', piles: ['obj → #crc n'], description: 'Somme de contrôle et taille en octets de l’objet.', details: 'Pratique pour vérifier qu’un transfert est intact.' },
  { nom: 'VERSION', sujet: 'Programmation', piles: ['→ "ver" "copyright"'], description: 'Version du système d’exploitation.' },
  { nom: 'TICKS', sujet: 'Programmation', piles: ['→ #n'], description: 'Horloge système en tics de 1/8192 s — idéal pour chronométrer du code.', details: 'Durée = (fin début −) B→R 8192 /.' },

  // ── Erreurs ──────────────────────────────────────────────────────────
  { nom: 'IFERR…THEN…END', sujet: 'Erreurs', piles: ['IFERR essai THEN rattrapage END'], description: 'Exécute l’essai ; en cas d’erreur, exécute le rattrapage au lieu de planter.', details: 'Variante IFERR…THEN…ELSE…END : ELSE s’exécute si tout s’est bien passé.' },
  { nom: 'DOERR', sujet: 'Erreurs', piles: ['n →', '#n →', '"message" →', '0 → (simule ATTN)'], description: 'Déclenche une erreur : numéro système ou message personnalisé.' },
  { nom: 'ERRN', sujet: 'Erreurs', piles: ['→ #n'], description: 'Numéro de la dernière erreur.', details: '#70000h pour une erreur DOERR avec chaîne.' },
  { nom: 'ERRM', sujet: 'Erreurs', piles: ['→ "message"'], description: 'Message de la dernière erreur.' },
  { nom: 'ERR0', sujet: 'Erreurs', description: 'Remet le numéro de la dernière erreur à zéro.' },

  // ── Mémoire & variables ──────────────────────────────────────────────
  { nom: 'STO', sujet: 'Mémoire & variables', piles: ['obj \'nom\' →', 'obj :port:nom →', 'grob PICT →'], description: 'Stocke l’objet dans une variable, un port ou PICT.', details: 'Écrase sans prévenir une variable existante.' },
  { nom: 'RCL', sujet: 'Mémoire & variables', piles: ['\'nom\' → obj', ':port:nom → obj', 'PICT → grob'], description: 'Rappelle le contenu d’une variable sans l’évaluer.' },
  { nom: 'PURGE', sujet: 'Mémoire & variables', piles: ['\'nom\' →', '{ noms } →', ':port:nom →'], description: 'Supprime une ou plusieurs variables.', details: 'Un répertoire doit être vide (sinon PGDIR).' },
  { nom: 'STO+', sujet: 'Mémoire & variables', piles: ['obj \'nom\' →', '\'nom\' obj →'], description: 'Ajoute au contenu de la variable (nom + obj).' },
  { nom: 'STO-', sujet: 'Mémoire & variables', piles: ['obj \'nom\' →', '\'nom\' obj →'], description: 'Soustrait au contenu de la variable.', details: 'L’ordre des arguments détermine le sens de la soustraction.' },
  { nom: 'STO*', sujet: 'Mémoire & variables', piles: ['obj \'nom\' →', '\'nom\' obj →'], description: 'Multiplie le contenu de la variable.' },
  { nom: 'STO/', sujet: 'Mémoire & variables', piles: ['obj \'nom\' →', '\'nom\' obj →'], description: 'Divise le contenu de la variable.' },
  { nom: 'INCR', sujet: 'Mémoire & variables', piles: ['\'nom\' → x+1'], description: 'Incrémente la variable de 1 et renvoie la nouvelle valeur.' },
  { nom: 'DECR', sujet: 'Mémoire & variables', piles: ['\'nom\' → x−1'], description: 'Décrémente la variable de 1 et renvoie la nouvelle valeur.' },
  { nom: 'VARS', sujet: 'Mémoire & variables', piles: ['→ { noms }'], description: 'Liste des variables du répertoire courant, dans l’ordre du menu VAR.' },
  { nom: 'TVARS', sujet: 'Mémoire & variables', piles: ['n → { noms }', '{ n… } → { noms }'], description: 'Variables du ou des types donnés (numéros TYPE) dans le répertoire courant.' },
  { nom: 'ORDER', sujet: 'Mémoire & variables', piles: ['{ noms } →'], description: 'Réordonne le menu VAR : les variables listées passent en tête.' },
  { nom: 'PATH', sujet: 'Mémoire & variables', piles: ['→ { HOME dir… }'], description: 'Chemin complet du répertoire courant.', details: 'EVAL sur cette liste y retourne.' },
  { nom: 'HOME', sujet: 'Mémoire & variables', description: 'Retourne au répertoire racine.' },
  { nom: 'UPDIR', sujet: 'Mémoire & variables', description: 'Remonte d’un niveau de répertoire.' },
  { nom: 'CRDIR', sujet: 'Mémoire & variables', piles: ['\'nom\' →'], description: 'Crée un sous-répertoire dans le répertoire courant.' },
  { nom: 'PGDIR', sujet: 'Mémoire & variables', piles: ['\'nom\' →'], description: 'Supprime un répertoire et tout son contenu, récursivement.', details: 'Irréversible — à manier avec précaution.' },
  { nom: 'ARCHIVE', sujet: 'Mémoire & variables', piles: [':port:nom →'], description: 'Sauvegarde tout HOME dans un objet de sauvegarde en port.', details: 'Port 0 (RAM), 1 ou 2 (cartes). Restauration avec RESTORE.' },
  { nom: 'RESTORE', sujet: 'Mémoire & variables', piles: ['sauvegarde →'], description: 'Remplace tout HOME par la sauvegarde — tout le contenu actuel est perdu !' },
  { nom: 'NEWOB', sujet: 'Mémoire & variables', piles: ['obj → obj'], description: 'Crée une copie indépendante de l’objet, détachée de sa variable ou liste d’origine.', details: 'Permet de purger l’original sans « Object In Use ».' },
  { nom: 'FREE', sujet: 'Mémoire & variables', piles: ['{ } n →'], description: 'Libère une carte RAM fusionnée (48SX) — peu utile sur la G.', },

  // ── Listes ───────────────────────────────────────────────────────────
  { nom: '→LIST', sujet: 'Listes', piles: ['objₙ…obj₁ n → { objₙ…obj₁ }'], description: 'Regroupe les n premiers niveaux en une liste.' },
  { nom: 'LIST→', sujet: 'Listes', piles: ['{ objₙ…obj₁ } → objₙ…obj₁ n'], description: 'Éclate la liste sur la pile et renvoie le nombre d’éléments.' },
  { nom: 'OBJ→', sujet: 'Listes', piles: ['{ … } → obj… n', '"str" → obj…', '(x,y) → x y', '[…] → x… { dims }', ':tag:obj → obj "tag"', 'symb → arg… n \'fct\''], description: 'Décompose n’importe quel objet composite en ses constituants.', details: 'Sur une chaîne, équivaut à STR→ (évalue le texte).' },
  { nom: 'GET', sujet: 'Listes', piles: ['{ } n → obj', '[ ] n → x', '[[ ]] { i j } → x', '\'nom\' n → obj'], description: 'Extrait l’élément n d’une liste ou d’un tableau.', details: 'Indices à partir de 1. Erreur « Bad Argument Value » hors bornes.' },
  { nom: 'GETI', sujet: 'Listes', piles: ['{ } n → { } n+1 obj', '[[ ]] { i j } → [[ ]] { i j }⁺ x'], description: 'Comme GET mais laisse l’objet et l’index incrémenté — pour itérer.', details: 'Le drapeau −64 est levé quand l’index reboucle au début.' },
  { nom: 'PUT', sujet: 'Listes', piles: ['{ } n obj → { }', '[[ ]] { i j } x → [[ ]]', '\'nom\' n obj →'], description: 'Remplace l’élément n.' },
  { nom: 'PUTI', sujet: 'Listes', piles: ['{ } n obj → { } n+1', '[[ ]] { i j } x → [[ ]] { i j }⁺'], description: 'Comme PUT avec index incrémenté — pour remplir en boucle.' },
  { nom: 'SIZE', sujet: 'Listes', piles: ['{ } → n', '"str" → n', '[[ ]] → { n m }', 'grob → { #l #h }', 'symb → n'], description: 'Taille de l’objet : nombre d’éléments, de caractères, dimensions.' },
  { nom: 'HEAD', sujet: 'Listes', piles: ['{ a … } → a', '"abc" → "a"'], description: 'Premier élément d’une liste ou d’une chaîne.' },
  { nom: 'TAIL', sujet: 'Listes', piles: ['{ a b c } → { b c }', '"abc" → "bc"'], description: 'Tout sauf le premier élément.' },
  { nom: 'POS', sujet: 'Listes', piles: ['{ } obj → n', '"str" "sous" → n'], description: 'Position de la première occurrence (0 si absent).' },
  { nom: 'SUB', sujet: 'Listes', piles: ['{ } n m → { }', '"str" n m → "str"', 'grob { #x₁ #y₁ } { #x₂ #y₂ } → grob'], description: 'Extrait une portion : éléments n à m, ou zone rectangulaire d’un GROB.' },
  { nom: 'REPL', sujet: 'Listes', piles: ['{ } n { } → { }', '"str" n "s" → "str"', 'grob { #x #y } g2 → grob', 'PICT { #x #y } g2 →'], description: 'Remplace une portion à partir de la position n (écrase, sans insérer).' },
  { nom: 'SORT', sujet: 'Listes', piles: ['{ } → { } trié'], description: 'Trie la liste en ordre croissant (nombres, chaînes…).' },
  { nom: 'REVLIST', sujet: 'Listes', piles: ['{ a b c } → { c b a }'], description: 'Inverse l’ordre des éléments.' },
  { nom: 'ΣLIST', sujet: 'Listes', piles: ['{ x… } → somme'], description: 'Somme de tous les éléments.' },
  { nom: 'ΠLIST', sujet: 'Listes', piles: ['{ x… } → produit'], description: 'Produit de tous les éléments.' },
  { nom: 'ΔLIST', sujet: 'Listes', piles: ['{ x₁ x₂ … } → { x₂−x₁ … }'], description: 'Différences entre éléments consécutifs (la liste raccourcit de 1).' },
  { nom: 'DOLIST', sujet: 'Listes', piles: ['{ l₁ }…{ lₙ } n « prog » → { }', '{ l } « prog » → { }'], description: 'Applique un programme à chaque élément de n listes en parallèle (map).', details: 'Sans n explicite si le programme est un objet à nombre d’arguments connu.' },
  { nom: 'DOSUB', sujet: 'Listes', piles: ['{ } n « prog » → { }'], description: 'Applique le programme à chaque fenêtre glissante de n éléments.' },
  { nom: 'STREAM', sujet: 'Listes', piles: ['{ x₁ x₂ … } « prog » → obj'], description: 'Réduit la liste : applique le programme binaire de proche en proche (fold).', details: '{ 1 2 3 4 } « + » STREAM → 10.' },
  { nom: 'SEQ', sujet: 'Listes', piles: ['« prog » \'var\' début fin pas → { }'], description: 'Génère la liste des valeurs de prog pour var allant de début à fin.', details: '« \'X^2\' » \'X\' 1 4 1 SEQ → { 1 4 9 16 }.' },
  { nom: 'ADD', sujet: 'Listes', piles: ['{ } { } → { }', '{ } x → { }'], description: 'Addition élément par élément (contrairement à + qui concatène).' },

  // ── Chaînes ──────────────────────────────────────────────────────────
  { nom: '→STR', sujet: 'Chaînes', piles: ['obj → "obj"'], description: 'Convertit n’importe quel objet en sa représentation texte.', details: 'Respecte le format d’affichage courant (STD, FIX…).' },
  { nom: 'STR→', sujet: 'Chaînes', piles: ['"texte" → obj…'], description: 'Interprète la chaîne comme du RPL et l’évalue (parse + EVAL).' },
  { nom: 'CHR', sujet: 'Chaînes', piles: ['n → "c"'], description: 'Caractère de code n (0–255).' },
  { nom: 'NUM', sujet: 'Chaînes', piles: ['"c…" → n'], description: 'Code du premier caractère de la chaîne.' },
  { nom: '→TAG', sujet: 'Chaînes', piles: ['obj "tag" → :tag:obj', 'obj \'nom\' → :nom:obj'], description: 'Étiquette un objet — pratique pour nommer des résultats.', details: 'L’étiquette est ignorée par les calculs.' },
  { nom: 'DTAG', sujet: 'Chaînes', piles: [':tag:obj → obj'], description: 'Retire l’étiquette (toutes les étiquettes imbriquées).' },

  // ── Matrices & vecteurs ──────────────────────────────────────────────
  { nom: '→ARRY', sujet: 'Matrices & vecteurs', piles: ['x₁…xₙ { n } → [ ]', 'x₁₁…xₙₘ { n m } → [[ ]]'], description: 'Assemble les nombres de la pile en vecteur ou matrice.' },
  { nom: 'ARRY→', sujet: 'Matrices & vecteurs', piles: ['[ ] → x… { n }', '[[ ]] → x… { n m }'], description: 'Éclate un tableau sur la pile, ligne par ligne, avec ses dimensions.' },
  { nom: 'CON', sujet: 'Matrices & vecteurs', piles: ['{ n m } x → [[x…]]', '[[ ]] x → [[x…]]', '\'nom\' x →'], description: 'Tableau constant : toutes les cases valent x.' },
  { nom: 'IDN', sujet: 'Matrices & vecteurs', piles: ['n → [[I]]', '[[ ]] → [[I]]', '\'nom\' →'], description: 'Matrice identité n×n.' },
  { nom: 'RDM', sujet: 'Matrices & vecteurs', piles: ['[…] { n m } → […]', '\'nom\' { n m } →'], description: 'Redimensionne : mêmes éléments, nouvelles dimensions (ordre ligne par ligne).' },
  { nom: 'TRN', sujet: 'Matrices & vecteurs', piles: ['[[ ]] → [[ᵀ]]', '\'nom\' →'], description: 'Transpose la matrice (transconjuguée pour les complexes).' },
  { nom: 'DET', sujet: 'Matrices & vecteurs', piles: ['[[ ]] → x'], description: 'Déterminant d’une matrice carrée.' },
  { nom: 'CROSS', sujet: 'Matrices & vecteurs', piles: ['[a] [b] → [a×b]'], description: 'Produit vectoriel de deux vecteurs 2D ou 3D.' },
  { nom: 'DOT', sujet: 'Matrices & vecteurs', piles: ['[a] [b] → x'], description: 'Produit scalaire.' },
  { nom: 'RSD', sujet: 'Matrices & vecteurs', piles: ['[B] [[A]] [X] → [B−AX]'], description: 'Résidu B−AX, pour affiner la solution d’un système linéaire.' },
  { nom: 'RNRM', sujet: 'Matrices & vecteurs', piles: ['[…] → x'], description: 'Norme de ligne : maximum des sommes des valeurs absolues par ligne.' },
  { nom: 'CNRM', sujet: 'Matrices & vecteurs', piles: ['[…] → x'], description: 'Norme de colonne.' },
  { nom: 'V→', sujet: 'Matrices & vecteurs', piles: ['[x y] → x y', '[x y z] → x y z'], description: 'Décompose un vecteur 2D/3D selon le mode de coordonnées courant (rectangulaire, polaire, sphérique).' },
  { nom: '→V2', sujet: 'Matrices & vecteurs', piles: ['x y → [x y]'], description: 'Assemble un vecteur 2D (interprété selon le mode de coordonnées).' },
  { nom: '→V3', sujet: 'Matrices & vecteurs', piles: ['x y z → [x y z]'], description: 'Assemble un vecteur 3D.' },

  // ── Graphismes & GROB ────────────────────────────────────────────────
  { nom: '→GROB', sujet: 'Graphismes & GROB', piles: ['obj n → grob'], description: 'Convertit un objet en image GROB, n = taille de police.', details: 'n : 0 utilise la plus grande police adaptée, 1 petite, 2 moyenne, 3 grande.' },
  { nom: 'LCD→', sujet: 'Graphismes & GROB', piles: ['→ grob 131×64'], description: 'Capture l’écran courant dans un GROB.' },
  { nom: '→LCD', sujet: 'Graphismes & GROB', piles: ['grob →'], description: 'Affiche le GROB directement sur l’écran (coin haut-gauche).' },
  { nom: 'BLANK', sujet: 'Graphismes & GROB', piles: ['#largeur #hauteur → grob'], description: 'Crée un GROB vide (tous pixels éteints).' },
  { nom: 'GOR', sujet: 'Graphismes & GROB', piles: ['g₁ { #x #y } g₂ → g', 'PICT { #x #y } g₂ →', 'g₁ (x,y) g₂ → g'], description: 'Superpose g₂ sur g₁ à la position donnée — OU logique des pixels.', details: 'Avec PICT en niveau 3, dessine directement dans l’écran graphique.' },
  { nom: 'GXOR', sujet: 'Graphismes & GROB', piles: ['g₁ { #x #y } g₂ → g', 'PICT { #x #y } g₂ →'], description: 'Superpose en OU exclusif — refaire la même opération efface (idéal pour un curseur).' },
  { nom: 'PICT', sujet: 'Graphismes & GROB', piles: ['→ PICT'], description: 'Le nom de l’écran graphique — cible pour STO, RCL, GOR, REPL…', details: 'RCL sur PICT renvoie son GROB ; PICT STO y place un GROB.' },
  { nom: 'PVIEW', sujet: 'Graphismes & GROB', piles: ['{ #x #y } →', '(x,y) →'], description: 'Affiche PICT à l’écran, coin haut-gauche à la position donnée, et gèle l’affichage.', details: '{ } vide : affiche avec défilement interactif.' },
  { nom: 'PIXON', sujet: 'Graphismes & GROB', piles: ['{ #x #y } →', '(x,y) →'], description: 'Allume un pixel de PICT (coordonnées pixel # ou utilisateur).' },
  { nom: 'PIXOFF', sujet: 'Graphismes & GROB', piles: ['{ #x #y } →', '(x,y) →'], description: 'Éteint un pixel de PICT.' },
  { nom: 'PIX?', sujet: 'Graphismes & GROB', piles: ['{ #x #y } → 0/1'], description: 'Teste l’état d’un pixel.' },
  { nom: 'LINE', sujet: 'Graphismes & GROB', piles: ['(x₁,y₁) (x₂,y₂) →', '{ #x₁ #y₁ } { #x₂ #y₂ } →'], description: 'Trace une ligne dans PICT entre les deux points.' },
  { nom: 'TLINE', sujet: 'Graphismes & GROB', piles: ['(x₁,y₁) (x₂,y₂) →'], description: 'Ligne en mode bascule : chaque pixel traversé est inversé.' },
  { nom: 'BOX', sujet: 'Graphismes & GROB', piles: ['(x₁,y₁) (x₂,y₂) →', '{ #x₁ #y₁ } { #x₂ #y₂ } →'], description: 'Rectangle dont les deux points sont les coins opposés.' },
  { nom: 'ARC', sujet: 'Graphismes & GROB', piles: ['(x,y) r θ₁ θ₂ →', '{ #x #y } #r θ₁ θ₂ →'], description: 'Arc de cercle de centre et rayon donnés, de θ₁ à θ₂.', details: 'Angles selon le mode angulaire courant. Cercle complet : 0 à 360°.' },
  { nom: 'TEXT', sujet: 'Graphismes & GROB', description: 'Réaffiche l’écran pile (sort de l’affichage graphique).' },
  { nom: 'PX→C', sujet: 'Graphismes & GROB', piles: ['{ #x #y } → (x,y)'], description: 'Convertit des coordonnées pixel en coordonnées utilisateur.' },
  { nom: 'C→PX', sujet: 'Graphismes & GROB', piles: ['(x,y) → { #x #y }'], description: 'Convertit des coordonnées utilisateur en pixels.' },
  { nom: 'PDIM', sujet: 'Graphismes & GROB', piles: ['#largeur #hauteur →', '(xmin,ymin) (xmax,ymax) →'], description: 'Redimensionne PICT (131×64 minimum).', details: 'Avec des complexes, ajuste aussi XRNG/YRNG.' },
  { nom: 'ANIMATE', sujet: 'Graphismes & GROB', piles: ['g₁…gₙ n → g₁…gₙ n', 'g₁…gₙ { n { #x #y } délai rep } → …'], description: 'Anime une suite de GROBs à l’écran.', details: 'délai en secondes, rep = nombre de cycles (0 = infini, ATTN pour arrêter).' },

  // ── Tracé de courbes ─────────────────────────────────────────────────
  { nom: 'STEQ', sujet: 'Tracé de courbes', piles: ['expr →'], description: 'Stocke l’expression dans EQ, l’équation courante du traceur et du solveur.' },
  { nom: 'RCEQ', sujet: 'Tracé de courbes', piles: ['→ expr'], description: 'Rappelle EQ sans l’évaluer.' },
  { nom: 'DRAW', sujet: 'Tracé de courbes', description: 'Trace EQ dans PICT selon le mode de tracé courant.', details: 'Ne dessine pas les axes — les ajouter avec DRAX.' },
  { nom: 'DRAX', sujet: 'Tracé de courbes', description: 'Trace les axes avec graduations.' },
  { nom: 'ERASE', sujet: 'Tracé de courbes', description: 'Efface PICT (tous pixels éteints).' },
  { nom: 'AUTO', sujet: 'Tracé de courbes', description: 'Ajuste automatiquement l’échelle verticale à la courbe.', details: 'Échantillonne EQ sur l’intervalle horizontal courant.' },
  { nom: 'XRNG', sujet: 'Tracé de courbes', piles: ['xmin xmax →'], description: 'Fixe l’intervalle horizontal du repère.' },
  { nom: 'YRNG', sujet: 'Tracé de courbes', piles: ['ymin ymax →'], description: 'Fixe l’intervalle vertical.' },
  { nom: 'INDEP', sujet: 'Tracé de courbes', piles: ['\'nom\' →', '{ nom début fin } →'], description: 'Variable indépendante du tracé, avec bornes optionnelles.' },
  { nom: 'DEPND', sujet: 'Tracé de courbes', piles: ['\'nom\' →'], description: 'Variable dépendante (utile en tracé d’équations différentielles).' },
  { nom: 'FUNCTION', sujet: 'Tracé de courbes', description: 'Mode de tracé « fonction » y=f(x).', details: 'Autres modes : POLAR, PARAMETRIC, CONIC, TRUTH, BAR, HISTOGRAM, SCATTER…' },
  { nom: 'ROOT', sujet: 'Tracé de courbes', piles: ['expr \'var\' x₀ → x', 'expr \'var\' { borne₁ borne₂ } → x'], description: 'Résout numériquement expr=0 près de la valeur initiale x₀.', details: 'C’est le moteur du solveur numérique (HP Solve).' },

  // ── Symbolique ───────────────────────────────────────────────────────
  { nom: 'COLCT', sujet: 'Symbolique', piles: ['symb → symb'], description: 'Simplifie en regroupant les termes semblables.' },
  { nom: 'EXPAN', sujet: 'Symbolique', piles: ['symb → symb'], description: 'Développe les produits, puissances et distributions.', details: 'Une seule passe — répéter pour tout développer.' },
  { nom: 'ISOL', sujet: 'Symbolique', piles: ['symb \'var\' → symb'], description: 'Isole la variable dans l’équation ou l’expression (=0 implicite).', details: 'La variable ne doit apparaître qu’une fois (sinon voir QUAD ou SHOW). Drapeau −1 : solution principale.' },
  { nom: 'QUAD', sujet: 'Symbolique', piles: ['symb \'var\' → symb'], description: 'Résout un polynôme du second degré en var (les deux racines via s1=±1).' },
  { nom: 'SHOW', sujet: 'Symbolique', piles: ['symb \'var\' → symb', 'symb { vars } → symb'], description: 'Ré-exprime en rendant la variable explicite partout où elle est cachée dans d’autres noms.' },
  { nom: 'TAYLR', sujet: 'Symbolique', piles: ['symb \'var\' n → symb'], description: 'Développement de Taylor à l’ordre n autour de var=0 (Maclaurin).' },
  { nom: '∂', sujet: 'Symbolique', piles: ['symb \'var\' → symb', '∂var(expr) en algébrique'], description: 'Dérivée par rapport à la variable.', details: 'Dérivation pas à pas si l’expression est en niveau 1 sans apostrophes.' },
  { nom: '∫', sujet: 'Symbolique', piles: ['a b symb \'var\' → x', '∫(a,b,expr,var) en algébrique'], description: 'Intégrale définie de a à b — numérique, ou symbolique pour les polynômes.', details: 'La précision numérique suit le format d’affichage (FIX n = tolérance).' },
  { nom: '|', sujet: 'Symbolique', piles: ['symb { var val … } → symb'], description: 'Substitution « où » : remplace les variables par les valeurs sans les stocker.', details: '\'X^2\' { X 3 } | → 9.' },
  { nom: 'APPLY', sujet: 'Symbolique', piles: ['{ args } \'fct\' → \'fct(args)\''], description: 'Construit l’expression fct(args) sans l’évaluer.' },
  { nom: 'QUOTE', sujet: 'Symbolique', piles: ['symb → symb'], description: 'Protège une expression contre l’évaluation.' },
  { nom: 'DEFINE', sujet: 'Symbolique', piles: ['\'nom=expr\' →', '\'f(x)=expr\' →'], description: 'Crée une variable ou une fonction utilisateur depuis une équation.', details: '\'F(X)=X^2+1\' DEFINE crée F utilisable dans les expressions.' },

  // ── Statistiques ─────────────────────────────────────────────────────
  { nom: 'Σ+', sujet: 'Statistiques', piles: ['x →', '[x₁ … xₘ] →', '[[…]] →'], description: 'Ajoute un point (ou plusieurs) à la matrice de données ΣDAT.', details: 'Crée ΣDAT si elle n’existe pas.' },
  { nom: 'Σ-', sujet: 'Statistiques', piles: ['→ x', '→ [x₁ … xₘ]'], description: 'Retire le dernier point de ΣDAT et le remet sur la pile.' },
  { nom: 'CLΣ', sujet: 'Statistiques', description: 'Purge ΣDAT (efface toutes les données statistiques).' },
  { nom: 'STOΣ', sujet: 'Statistiques', piles: ['obj →'], description: 'Stocke l’objet (matrice) dans ΣDAT.' },
  { nom: 'RCLΣ', sujet: 'Statistiques', piles: ['→ ΣDAT'], description: 'Rappelle la matrice de données ΣDAT.' },
  { nom: 'NΣ', sujet: 'Statistiques', piles: ['→ n'], description: 'Nombre de points de données dans ΣDAT.' },
  { nom: 'MEAN', sujet: 'Statistiques', piles: ['→ x', '→ [x̄₁ … x̄ₘ]'], description: 'Moyenne de chaque colonne de ΣDAT.' },
  { nom: 'SDEV', sujet: 'Statistiques', piles: ['→ x', '→ [s₁ … sₘ]'], description: 'Écart-type échantillon (diviseur n−1).' },
  { nom: 'PSDEV', sujet: 'Statistiques', piles: ['→ x'], description: 'Écart-type population (diviseur n).' },
  { nom: 'VAR', sujet: 'Statistiques', piles: ['→ x'], description: 'Variance échantillon de chaque colonne.' },
  { nom: 'TOT', sujet: 'Statistiques', piles: ['→ x', '→ [t₁ … tₘ]'], description: 'Somme de chaque colonne.' },
  { nom: 'MAXΣ', sujet: 'Statistiques', piles: ['→ x'], description: 'Maximum de chaque colonne.' },
  { nom: 'MINΣ', sujet: 'Statistiques', piles: ['→ x'], description: 'Minimum de chaque colonne.' },
  { nom: 'CORR', sujet: 'Statistiques', piles: ['→ r'], description: 'Coefficient de corrélation entre les colonnes XCOL et YCOL.' },
  { nom: 'COV', sujet: 'Statistiques', piles: ['→ x'], description: 'Covariance échantillon.' },
  { nom: 'LR', sujet: 'Statistiques', piles: ['→ :Intercept:b :Slope:m'], description: 'Régression linéaire sur XCOL/YCOL selon le modèle courant.', details: 'Modèles : LINFIT, LOGFIT, EXPFIT, PWRFIT, BESTFIT.' },
  { nom: 'PREDY', sujet: 'Statistiques', piles: ['x → y'], description: 'Prédit y pour un x donné, selon la dernière régression.' },
  { nom: 'PREDX', sujet: 'Statistiques', piles: ['y → x'], description: 'Prédit x pour un y donné.' },
  { nom: 'XCOL', sujet: 'Statistiques', piles: ['n →'], description: 'Choisit la colonne indépendante de ΣDAT.' },
  { nom: 'YCOL', sujet: 'Statistiques', piles: ['n →'], description: 'Choisit la colonne dépendante.' },
  { nom: 'UTPN', sujet: 'Statistiques', piles: ['moy var x → p'], description: 'Queue supérieure de la loi normale : P(X>x).', details: 'Aussi UTPT (Student), UTPC (χ²), UTPF (Fisher).' },

  // ── Unités ───────────────────────────────────────────────────────────
  { nom: '→UNIT', sujet: 'Unités', piles: ['x 1_unité → x_unité'], description: 'Attache l’unité du niveau 1 au nombre du niveau 2.' },
  { nom: 'UBASE', sujet: 'Unités', piles: ['x_u → y_SI'], description: 'Convertit vers les unités SI de base.', details: '1_km UBASE → 1000_m.' },
  { nom: 'UVAL', sujet: 'Unités', piles: ['x_u → x'], description: 'La valeur numérique, sans l’unité.' },
  { nom: 'CONVERT', sujet: 'Unités', piles: ['x_u₁ 1_u₂ → y_u₂'], description: 'Convertit d’une unité vers une autre unité compatible.', details: '25_m 1_ft CONVERT → 82.02…_ft. « Inconsistent Units » si incompatibles.' },
  { nom: 'UFACT', sujet: 'Unités', piles: ['x_u₁ 1_u₂ → y_u₂·u₁/u₂'], description: 'Factorise l’unité u₂ dans l’unité composée.' },

  // ── Heure & date ─────────────────────────────────────────────────────
  { nom: 'DATE', sujet: 'Heure & date', piles: ['→ date'], description: 'Date courante, au format MM.JJAAAA ou JJ.MMAAAA selon le drapeau −42.' },
  { nom: 'TIME', sujet: 'Heure & date', piles: ['→ HH.MMSS'], description: 'Heure courante en notation HH.MMSSs.' },
  { nom: '→DATE', sujet: 'Heure & date', piles: ['date →'], description: 'Règle la date de l’horloge système.' },
  { nom: '→TIME', sujet: 'Heure & date', piles: ['HH.MMSS →'], description: 'Règle l’heure de l’horloge système.' },
  { nom: 'DATE+', sujet: 'Heure & date', piles: ['date n → date'], description: 'Ajoute n jours (négatif pour reculer) à une date.' },
  { nom: 'DDAYS', sujet: 'Heure & date', piles: ['date₁ date₂ → n'], description: 'Nombre de jours entre deux dates.' },
  { nom: '→HMS', sujet: 'Heure & date', piles: ['x → HH.MMSS'], description: 'Convertit des heures décimales en heures-minutes-secondes.', details: '1.5 →HMS → 1.30 (1 h 30 min).' },
  { nom: 'HMS→', sujet: 'Heure & date', piles: ['HH.MMSS → x'], description: 'Convertit HH.MMSS en heures décimales.' },
  { nom: 'HMS+', sujet: 'Heure & date', piles: ['hms₁ hms₂ → hms'], description: 'Additionne deux durées en notation HMS.' },
  { nom: 'HMS-', sujet: 'Heure & date', piles: ['hms₁ hms₂ → hms'], description: 'Soustrait deux durées en HMS.' },
  { nom: 'TSTR', sujet: 'Heure & date', piles: ['date heure → "str"'], description: 'Formate date et heure en chaîne lisible (« TUE 30.08.26 12:00:00 »).' },

  // ── Affichage & clavier ──────────────────────────────────────────────
  { nom: 'DISP', sujet: 'Affichage & clavier', piles: ['obj n →'], description: 'Affiche l’objet sur la ligne n de l’écran (1 en haut, 7 en bas).', details: 'Suivre d’un FREEZE pour que l’affichage reste visible.' },
  { nom: 'CLLCD', sujet: 'Affichage & clavier', description: 'Efface l’écran (l’affichage pile revient à la prochaine mise à jour — voir FREEZE).' },
  { nom: 'FREEZE', sujet: 'Affichage & clavier', piles: ['n →'], description: 'Gèle des zones d’écran jusqu’à la prochaine touche.', details: 'n additif : 1 zone d’état, 2 pile/ligne de commande, 4 menu. 7 = tout l’écran.' },
  { nom: 'MSGBOX', sujet: 'Affichage & clavier', piles: ['"message" →'], description: 'Affiche le message dans une boîte de dialogue avec OK.' },
  { nom: 'PROMPT', sujet: 'Affichage & clavier', piles: ['"message" →'], description: 'Affiche le message dans la zone d’état et suspend le programme.', details: 'L’utilisateur répond puis relance avec CONT.' },
  { nom: 'INPUT', sujet: 'Affichage & clavier', piles: ['"message" "défaut" → "réponse"', '"msg" { "défaut" pos mode } → "réponse"'], description: 'Saisie : affiche le message, pré-remplit la ligne de commande, renvoie la réponse en chaîne.', details: 'Faire STR→ (ou OBJ→) sur la réponse pour l’évaluer. Mode α ou algébrique via la liste d’options.' },
  { nom: 'INFORM', sujet: 'Affichage & clavier', piles: ['"titre" { champs } format { reset } { init } → 1 { valeurs } / 0'], description: 'Boîte de dialogue complète à plusieurs champs.', details: 'Renvoie 1 et les valeurs si OK, 0 si annulé.' },
  { nom: 'CHOOSE', sujet: 'Affichage & clavier', piles: ['"titre" { items } pos → 1 obj / 0'], description: 'Menu déroulant de choix dans une boîte.', details: 'Chaque item peut être { "libellé" valeur }.' },
  { nom: 'KEY', sujet: 'Affichage & clavier', piles: ['→ 0', '→ n 1'], description: 'Lit le tampon clavier sans attendre : 0 si aucune touche, sinon le code et 1.', details: 'À utiliser en boucle : DO UNTIL KEY END.' },
  { nom: 'BEEP', sujet: 'Affichage & clavier', piles: ['fréquence durée →'], description: 'Émet un son (fréquence en Hz, durée en secondes).', details: 'Silencieux si le drapeau −56 est levé.' },
  { nom: 'MENU', sujet: 'Affichage & clavier', piles: ['n →', '{ défs } →'], description: 'Affiche un menu : numéro de menu système ou menu personnalisé.', details: 'Définition : { { "libellé" « action » } … }. 62 MENU = ancien menu CST.' },
  { nom: 'TMENU', sujet: 'Affichage & clavier', piles: ['{ défs } →', 'n →'], description: 'Comme MENU mais temporaire : n’écrase pas la variable CST.' },
  { nom: 'RCLMENU', sujet: 'Affichage & clavier', piles: ['→ n.mm'], description: 'Numéro du menu affiché (avec la page en décimales).' },
  { nom: 'ASN', sujet: 'Affichage & clavier', piles: ['obj rc.p →'], description: 'Assigne un objet à une touche du clavier utilisateur.', details: 'rc.p : rangée-colonne.plan (plan 1 direct, 2 shift-gauche, 3 shift-droit, 4 α…). Activer avec USER.' },
  { nom: 'STOKEYS', sujet: 'Affichage & clavier', piles: ['{ obj rc.p … } →'], description: 'Assigne plusieurs touches d’un coup.' },
  { nom: 'RCLKEYS', sujet: 'Affichage & clavier', piles: ['→ { assignations }'], description: 'Liste des assignations du clavier utilisateur.' },
  { nom: 'DELKEYS', sujet: 'Affichage & clavier', piles: ['rc.p →', '{ rc.p … } →', '0 →'], description: 'Supprime des assignations (0 = toutes).' },
]
