// Dictionnaire des commandes de la HP48G.
// Signature de pile : « avant → après », niveau 1 à droite.

export type Commande = {
  nom: string
  sujet: string
  pile?: string
  description: string
}

export const SUJETS = [
  'Pile',
  'Maths réels',
  'Complexes',
  'Binaire & bits',
  'Tests & logique',
  'Programmation',
  'Erreurs',
  'Mémoire & variables',
  'Listes',
  'Chaînes',
  'Matrices & vecteurs',
  'Graphismes & GROB',
  'Tracé de courbes',
  'Symbolique',
  'Statistiques',
  'Unités',
  'Heure & date',
  'Affichage & clavier',
] as const

export const COMMANDES: Commande[] = [
  // Pile
  { nom: 'DUP', sujet: 'Pile', pile: 'obj → obj obj', description: 'Duplique l’objet du niveau 1.' },
  { nom: 'DUP2', sujet: 'Pile', pile: 'a b → a b a b', description: 'Duplique les deux premiers niveaux.' },
  { nom: 'DUPN', sujet: 'Pile', pile: 'obj… n → obj… obj…', description: 'Duplique les n premiers niveaux de la pile.' },
  { nom: 'DROP', sujet: 'Pile', pile: 'obj →', description: 'Supprime l’objet du niveau 1.' },
  { nom: 'DROP2', sujet: 'Pile', pile: 'a b →', description: 'Supprime les deux premiers niveaux.' },
  { nom: 'DROPN', sujet: 'Pile', pile: 'obj… n →', description: 'Supprime les n premiers niveaux.' },
  { nom: 'SWAP', sujet: 'Pile', pile: 'a b → b a', description: 'Échange les niveaux 1 et 2.' },
  { nom: 'OVER', sujet: 'Pile', pile: 'a b → a b a', description: 'Copie le niveau 2 au niveau 1.' },
  { nom: 'ROT', sujet: 'Pile', pile: 'a b c → b c a', description: 'Fait tourner les trois premiers niveaux (le 3 passe au 1).' },
  { nom: 'ROLL', sujet: 'Pile', pile: 'obj… n → obj…', description: 'Fait remonter le niveau n au niveau 1.' },
  { nom: 'ROLLD', sujet: 'Pile', pile: 'obj… n → obj…', description: 'Fait descendre le niveau 1 au niveau n.' },
  { nom: 'PICK', sujet: 'Pile', pile: 'obj… n → obj… obj', description: 'Copie le niveau n au niveau 1.' },
  { nom: 'DEPTH', sujet: 'Pile', pile: '→ n', description: 'Renvoie le nombre d’objets sur la pile.' },
  { nom: 'CLEAR', sujet: 'Pile', pile: 'obj… →', description: 'Vide entièrement la pile.' },
  { nom: 'LASTARG', sujet: 'Pile', pile: '→ obj…', description: 'Remet sur la pile les arguments de la dernière commande.' },

  // Maths réels
  { nom: '+', sujet: 'Maths réels', pile: 'a b → a+b', description: 'Addition (marche aussi sur listes, chaînes, matrices…).' },
  { nom: '-', sujet: 'Maths réels', pile: 'a b → a−b', description: 'Soustraction.' },
  { nom: '*', sujet: 'Maths réels', pile: 'a b → a·b', description: 'Multiplication.' },
  { nom: '/', sujet: 'Maths réels', pile: 'a b → a/b', description: 'Division.' },
  { nom: '^', sujet: 'Maths réels', pile: 'a b → a^b', description: 'Puissance.' },
  { nom: 'INV', sujet: 'Maths réels', pile: 'x → 1/x', description: 'Inverse (aussi matrice inverse).' },
  { nom: 'NEG', sujet: 'Maths réels', pile: 'x → −x', description: 'Change le signe.' },
  { nom: 'SQ', sujet: 'Maths réels', pile: 'x → x²', description: 'Carré.' },
  { nom: '√', sujet: 'Maths réels', pile: 'x → √x', description: 'Racine carrée.' },
  { nom: 'XROOT', sujet: 'Maths réels', pile: 'x n → ⁿ√x', description: 'Racine n-ième.' },
  { nom: 'SIN', sujet: 'Maths réels', pile: 'x → sin x', description: 'Sinus (selon le mode angulaire).' },
  { nom: 'COS', sujet: 'Maths réels', pile: 'x → cos x', description: 'Cosinus.' },
  { nom: 'TAN', sujet: 'Maths réels', pile: 'x → tan x', description: 'Tangente.' },
  { nom: 'ASIN', sujet: 'Maths réels', pile: 'x → arcsin x', description: 'Arc sinus.' },
  { nom: 'ACOS', sujet: 'Maths réels', pile: 'x → arccos x', description: 'Arc cosinus.' },
  { nom: 'ATAN', sujet: 'Maths réels', pile: 'x → arctan x', description: 'Arc tangente.' },
  { nom: 'EXP', sujet: 'Maths réels', pile: 'x → eˣ', description: 'Exponentielle.' },
  { nom: 'LN', sujet: 'Maths réels', pile: 'x → ln x', description: 'Logarithme népérien.' },
  { nom: 'LOG', sujet: 'Maths réels', pile: 'x → log x', description: 'Logarithme décimal.' },
  { nom: 'ALOG', sujet: 'Maths réels', pile: 'x → 10ˣ', description: 'Antilogarithme (10 puissance x).' },
  { nom: 'ABS', sujet: 'Maths réels', pile: 'x → |x|', description: 'Valeur absolue (ou module, ou norme).' },
  { nom: 'SIGN', sujet: 'Maths réels', pile: 'x → −1/0/1', description: 'Signe du nombre.' },
  { nom: 'IP', sujet: 'Maths réels', pile: 'x → int(x)', description: 'Partie entière (troncature).' },
  { nom: 'FP', sujet: 'Maths réels', pile: 'x → frac(x)', description: 'Partie fractionnaire.' },
  { nom: 'FLOOR', sujet: 'Maths réels', pile: 'x → ⌊x⌋', description: 'Plus grand entier ≤ x.' },
  { nom: 'CEIL', sujet: 'Maths réels', pile: 'x → ⌈x⌉', description: 'Plus petit entier ≥ x.' },
  { nom: 'RND', sujet: 'Maths réels', pile: 'x n → x arrondi', description: 'Arrondit à n décimales.' },
  { nom: 'TRNC', sujet: 'Maths réels', pile: 'x n → x tronqué', description: 'Tronque à n décimales.' },
  { nom: 'MOD', sujet: 'Maths réels', pile: 'a b → a mod b', description: 'Reste de la division.' },
  { nom: 'MAX', sujet: 'Maths réels', pile: 'a b → max', description: 'Le plus grand des deux.' },
  { nom: 'MIN', sujet: 'Maths réels', pile: 'a b → min', description: 'Le plus petit des deux.' },
  { nom: '%', sujet: 'Maths réels', pile: 'a b → a·b/100', description: 'b pourcent de a.' },
  { nom: '%CH', sujet: 'Maths réels', pile: 'a b → 100·(b−a)/a', description: 'Variation en pourcentage de a vers b.' },
  { nom: '%T', sujet: 'Maths réels', pile: 'a b → 100·b/a', description: 'Pourcentage que représente b par rapport à a.' },
  { nom: 'RAND', sujet: 'Maths réels', pile: '→ x', description: 'Nombre aléatoire entre 0 et 1.' },
  { nom: 'RDZ', sujet: 'Maths réels', pile: 'x →', description: 'Initialise le générateur aléatoire (graine).' },
  { nom: '!', sujet: 'Maths réels', pile: 'n → n!', description: 'Factorielle (fonction gamma pour les non-entiers).' },
  { nom: 'COMB', sujet: 'Maths réels', pile: 'n k → C(n,k)', description: 'Combinaisons de n objets pris k à k.' },
  { nom: 'PERM', sujet: 'Maths réels', pile: 'n k → P(n,k)', description: 'Permutations de n objets pris k à k.' },
  { nom: 'MANT', sujet: 'Maths réels', pile: 'x → mantisse', description: 'Mantisse du nombre.' },
  { nom: 'XPON', sujet: 'Maths réels', pile: 'x → exposant', description: 'Exposant du nombre.' },
  { nom: 'GCD', sujet: 'Maths réels', pile: 'a b → pgcd', description: 'Plus grand commun diviseur (menu MTH).' },
  { nom: '→NUM', sujet: 'Maths réels', pile: 'symb → x', description: 'Évalue numériquement une expression symbolique.' },
  { nom: 'PI', sujet: 'Maths réels', pile: '→ π', description: 'La constante π (symbolique, →NUM pour la valeur).' },

  // Complexes
  { nom: 'RE', sujet: 'Complexes', pile: 'z → re(z)', description: 'Partie réelle.' },
  { nom: 'IM', sujet: 'Complexes', pile: 'z → im(z)', description: 'Partie imaginaire.' },
  { nom: 'ARG', sujet: 'Complexes', pile: 'z → arg(z)', description: 'Argument (angle) du complexe.' },
  { nom: 'CONJ', sujet: 'Complexes', pile: 'z → z̄', description: 'Conjugué.' },
  { nom: 'R→C', sujet: 'Complexes', pile: 'x y → (x,y)', description: 'Combine deux réels en un complexe.' },
  { nom: 'C→R', sujet: 'Complexes', pile: '(x,y) → x y', description: 'Sépare un complexe en deux réels.' },

  // Binaire & bits
  { nom: 'BIN', sujet: 'Binaire & bits', description: 'Base binaire pour les entiers # (mode).' },
  { nom: 'DEC', sujet: 'Binaire & bits', description: 'Base décimale pour les entiers #.' },
  { nom: 'HEX', sujet: 'Binaire & bits', description: 'Base hexadécimale pour les entiers #.' },
  { nom: 'OCT', sujet: 'Binaire & bits', description: 'Base octale pour les entiers #.' },
  { nom: 'STWS', sujet: 'Binaire & bits', pile: 'n →', description: 'Fixe la taille de mot (1–64 bits).' },
  { nom: 'RCWS', sujet: 'Binaire & bits', pile: '→ n', description: 'Renvoie la taille de mot courante.' },
  { nom: 'R→B', sujet: 'Binaire & bits', pile: 'x → #n', description: 'Réel vers entier binaire.' },
  { nom: 'B→R', sujet: 'Binaire & bits', pile: '#n → x', description: 'Entier binaire vers réel.' },
  { nom: 'SL', sujet: 'Binaire & bits', pile: '#n → #n', description: 'Décalage d’un bit vers la gauche.' },
  { nom: 'SR', sujet: 'Binaire & bits', pile: '#n → #n', description: 'Décalage d’un bit vers la droite.' },
  { nom: 'ASR', sujet: 'Binaire & bits', pile: '#n → #n', description: 'Décalage arithmétique à droite (conserve le bit de signe).' },
  { nom: 'RL', sujet: 'Binaire & bits', pile: '#n → #n', description: 'Rotation d’un bit vers la gauche.' },
  { nom: 'RR', sujet: 'Binaire & bits', pile: '#n → #n', description: 'Rotation d’un bit vers la droite.' },
  { nom: 'SLB', sujet: 'Binaire & bits', pile: '#n → #n', description: 'Décalage d’un octet vers la gauche.' },
  { nom: 'SRB', sujet: 'Binaire & bits', pile: '#n → #n', description: 'Décalage d’un octet vers la droite.' },

  // Tests & logique
  { nom: '==', sujet: 'Tests & logique', pile: 'a b → 0/1', description: 'Test d’égalité.' },
  { nom: '≠', sujet: 'Tests & logique', pile: 'a b → 0/1', description: 'Test de différence.' },
  { nom: '<', sujet: 'Tests & logique', pile: 'a b → 0/1', description: 'Strictement inférieur.' },
  { nom: '>', sujet: 'Tests & logique', pile: 'a b → 0/1', description: 'Strictement supérieur.' },
  { nom: '≤', sujet: 'Tests & logique', pile: 'a b → 0/1', description: 'Inférieur ou égal.' },
  { nom: '≥', sujet: 'Tests & logique', pile: 'a b → 0/1', description: 'Supérieur ou égal.' },
  { nom: 'SAME', sujet: 'Tests & logique', pile: 'a b → 0/1', description: 'Vrai si les deux objets sont identiques (comparaison stricte).' },
  { nom: 'AND', sujet: 'Tests & logique', pile: 'a b → 0/1', description: 'ET logique (ou bit à bit sur les #).' },
  { nom: 'OR', sujet: 'Tests & logique', pile: 'a b → 0/1', description: 'OU logique (ou bit à bit sur les #).' },
  { nom: 'XOR', sujet: 'Tests & logique', pile: 'a b → 0/1', description: 'OU exclusif.' },
  { nom: 'NOT', sujet: 'Tests & logique', pile: 'a → 0/1', description: 'Négation logique (ou complément sur les #).' },
  { nom: 'IFT', sujet: 'Tests & logique', pile: 'test obj →', description: 'Si test vrai, évalue l’objet.' },
  { nom: 'IFTE', sujet: 'Tests & logique', pile: 'test vrai faux →', description: 'Si test vrai évalue le 1er objet, sinon le 2e.' },
  { nom: 'TYPE', sujet: 'Tests & logique', pile: 'obj → n', description: 'Renvoie le numéro de type de l’objet (0=réel, 5=liste…).' },
  { nom: 'SF', sujet: 'Tests & logique', pile: 'n →', description: 'Met le drapeau n à 1.' },
  { nom: 'CF', sujet: 'Tests & logique', pile: 'n →', description: 'Met le drapeau n à 0.' },
  { nom: 'FS?', sujet: 'Tests & logique', pile: 'n → 0/1', description: 'Teste si le drapeau n est levé.' },
  { nom: 'FC?', sujet: 'Tests & logique', pile: 'n → 0/1', description: 'Teste si le drapeau n est baissé.' },
  { nom: 'FS?C', sujet: 'Tests & logique', pile: 'n → 0/1', description: 'Teste le drapeau n puis le baisse.' },
  { nom: 'FC?C', sujet: 'Tests & logique', pile: 'n → 0/1', description: 'Teste si baissé puis le baisse.' },

  // Programmation
  { nom: 'IF…THEN…END', sujet: 'Programmation', description: 'Structure conditionnelle : IF test THEN actions END.' },
  { nom: 'IF…THEN…ELSE…END', sujet: 'Programmation', description: 'Conditionnelle avec branche sinon.' },
  { nom: 'CASE…END', sujet: 'Programmation', description: 'Choix multiple : CASE test THEN … END … END.' },
  { nom: 'FOR…NEXT', sujet: 'Programmation', pile: 'début fin →', description: 'Boucle avec compteur nommé : début fin FOR i … NEXT.' },
  { nom: 'FOR…STEP', sujet: 'Programmation', pile: 'début fin →', description: 'Comme FOR…NEXT avec un pas explicite (STEP pas).' },
  { nom: 'START…NEXT', sujet: 'Programmation', pile: 'début fin →', description: 'Boucle sans variable de compteur.' },
  { nom: 'WHILE…REPEAT…END', sujet: 'Programmation', description: 'Boucle tant que : WHILE test REPEAT actions END.' },
  { nom: 'DO…UNTIL…END', sujet: 'Programmation', description: 'Boucle jusqu’à : DO actions UNTIL test END.' },
  { nom: '→', sujet: 'Programmation', pile: 'obj… →', description: 'Variables locales : → a b « … » lie a et b aux valeurs de la pile.' },
  { nom: 'EVAL', sujet: 'Programmation', pile: 'obj →', description: 'Évalue l’objet du niveau 1 (programme, nom, expression…).' },
  { nom: 'HALT', sujet: 'Programmation', description: 'Suspend le programme (reprise avec CONT).' },
  { nom: 'CONT', sujet: 'Programmation', description: 'Reprend un programme suspendu par HALT.' },
  { nom: 'KILL', sujet: 'Programmation', description: 'Arrête tous les programmes suspendus.' },
  { nom: 'WAIT', sujet: 'Programmation', pile: 'x →', description: 'Pause de x secondes (0 : attend une touche, −1 : affiche le menu).' },
  { nom: 'RCLF', sujet: 'Programmation', pile: '→ { #s #u }', description: 'Sauvegarde l’état des drapeaux.' },
  { nom: 'STOF', sujet: 'Programmation', pile: '{ #s #u } →', description: 'Restaure l’état des drapeaux.' },
  { nom: 'MEM', sujet: 'Programmation', pile: '→ n', description: 'Mémoire libre en octets.' },
  { nom: 'BYTES', sujet: 'Programmation', pile: 'obj → #crc n', description: 'Taille en octets et somme de contrôle d’un objet.' },
  { nom: 'VERSION', sujet: 'Programmation', pile: '→ str str', description: 'Version du système.' },

  // Erreurs
  { nom: 'IFERR…THEN…END', sujet: 'Erreurs', description: 'Capture d’erreur : IFERR actions THEN rattrapage END.' },
  { nom: 'DOERR', sujet: 'Erreurs', pile: 'n/str →', description: 'Déclenche une erreur (numéro ou message).' },
  { nom: 'ERRN', sujet: 'Erreurs', pile: '→ #n', description: 'Numéro de la dernière erreur.' },
  { nom: 'ERRM', sujet: 'Erreurs', pile: '→ str', description: 'Message de la dernière erreur.' },
  { nom: 'ERR0', sujet: 'Erreurs', description: 'Remet le numéro d’erreur à zéro.' },

  // Mémoire & variables
  { nom: 'STO', sujet: 'Mémoire & variables', pile: 'obj nom →', description: 'Stocke l’objet dans la variable.' },
  { nom: 'RCL', sujet: 'Mémoire & variables', pile: 'nom → obj', description: 'Rappelle le contenu de la variable.' },
  { nom: 'PURGE', sujet: 'Mémoire & variables', pile: 'nom →', description: 'Supprime une variable (ou une liste de variables).' },
  { nom: 'STO+', sujet: 'Mémoire & variables', pile: 'obj nom →', description: 'Ajoute au contenu de la variable.' },
  { nom: 'STO-', sujet: 'Mémoire & variables', pile: 'obj nom →', description: 'Soustrait au contenu de la variable.' },
  { nom: 'STO*', sujet: 'Mémoire & variables', pile: 'obj nom →', description: 'Multiplie le contenu de la variable.' },
  { nom: 'STO/', sujet: 'Mémoire & variables', pile: 'obj nom →', description: 'Divise le contenu de la variable.' },
  { nom: 'INCR', sujet: 'Mémoire & variables', pile: 'nom → x', description: 'Incrémente la variable et renvoie la nouvelle valeur.' },
  { nom: 'DECR', sujet: 'Mémoire & variables', pile: 'nom → x', description: 'Décrémente la variable et renvoie la nouvelle valeur.' },
  { nom: 'VARS', sujet: 'Mémoire & variables', pile: '→ { noms }', description: 'Liste des variables du répertoire courant.' },
  { nom: 'TVARS', sujet: 'Mémoire & variables', pile: 'n → { noms }', description: 'Variables du type donné dans le répertoire courant.' },
  { nom: 'ORDER', sujet: 'Mémoire & variables', pile: '{ noms } →', description: 'Réordonne le menu VAR.' },
  { nom: 'PATH', sujet: 'Mémoire & variables', pile: '→ { HOME … }', description: 'Chemin du répertoire courant.' },
  { nom: 'HOME', sujet: 'Mémoire & variables', description: 'Retourne au répertoire racine.' },
  { nom: 'UPDIR', sujet: 'Mémoire & variables', description: 'Remonte d’un répertoire.' },
  { nom: 'CRDIR', sujet: 'Mémoire & variables', pile: 'nom →', description: 'Crée un sous-répertoire.' },
  { nom: 'PGDIR', sujet: 'Mémoire & variables', pile: 'nom →', description: 'Supprime un répertoire et tout son contenu.' },
  { nom: 'ARCHIVE', sujet: 'Mémoire & variables', pile: 'nom →', description: 'Sauvegarde HOME dans un port (:port:nom).' },
  { nom: 'RESTORE', sujet: 'Mémoire & variables', pile: 'sauvegarde →', description: 'Restaure une sauvegarde de HOME (remplace tout !).' },
  { nom: 'NEWOB', sujet: 'Mémoire & variables', pile: 'obj → obj', description: 'Détache l’objet de sa source (copie indépendante).' },
  { nom: 'RCLΣ', sujet: 'Mémoire & variables', pile: '→ ΣDAT', description: 'Rappelle la matrice statistique ΣDAT.' },

  // Listes
  { nom: '→LIST', sujet: 'Listes', pile: 'obj… n → { }', description: 'Regroupe n objets en une liste.' },
  { nom: 'LIST→', sujet: 'Listes', pile: '{ } → obj… n', description: 'Éclate une liste sur la pile.' },
  { nom: 'OBJ→', sujet: 'Listes', pile: 'obj → …', description: 'Décompose un objet (liste, chaîne, complexe, tableau…).' },
  { nom: 'GET', sujet: 'Listes', pile: '{ } n → obj', description: 'Élément n d’une liste ou d’un tableau.' },
  { nom: 'GETI', sujet: 'Listes', pile: '{ } n → { } n+1 obj', description: 'GET avec index incrémenté (pour itérer).' },
  { nom: 'PUT', sujet: 'Listes', pile: '{ } n obj → { }', description: 'Remplace l’élément n.' },
  { nom: 'PUTI', sujet: 'Listes', pile: '{ } n obj → { } n+1', description: 'PUT avec index incrémenté.' },
  { nom: 'SIZE', sujet: 'Listes', pile: 'obj → n', description: 'Taille (liste, chaîne, tableau, GROB…).' },
  { nom: 'HEAD', sujet: 'Listes', pile: '{ } → obj', description: 'Premier élément.' },
  { nom: 'TAIL', sujet: 'Listes', pile: '{ } → { }', description: 'La liste sans son premier élément.' },
  { nom: 'POS', sujet: 'Listes', pile: '{ } obj → n', description: 'Position d’un élément (0 si absent).' },
  { nom: 'SUB', sujet: 'Listes', pile: '{ } n m → { }', description: 'Sous-liste (ou sous-chaîne, sous-GROB) de n à m.' },
  { nom: 'REPL', sujet: 'Listes', pile: '{ } n { } → { }', description: 'Remplace une portion à partir de la position n.' },
  { nom: 'SORT', sujet: 'Listes', pile: '{ } → { }', description: 'Trie la liste en ordre croissant.' },
  { nom: 'REVLIST', sujet: 'Listes', pile: '{ } → { }', description: 'Inverse l’ordre de la liste.' },
  { nom: 'ΣLIST', sujet: 'Listes', pile: '{ } → somme', description: 'Somme des éléments.' },
  { nom: 'ΠLIST', sujet: 'Listes', pile: '{ } → produit', description: 'Produit des éléments.' },
  { nom: 'ΔLIST', sujet: 'Listes', pile: '{ } → { }', description: 'Différences entre éléments consécutifs.' },
  { nom: 'DOLIST', sujet: 'Listes', pile: '{ }… n prog → { }', description: 'Applique un programme à n listes en parallèle.' },
  { nom: 'DOSUB', sujet: 'Listes', pile: '{ } n prog → { }', description: 'Applique un programme à chaque groupe de n éléments.' },
  { nom: 'STREAM', sujet: 'Listes', pile: '{ } prog → obj', description: 'Réduit la liste avec un programme binaire (fold).' },
  { nom: 'SEQ', sujet: 'Listes', pile: 'prog var deb fin pas → { }', description: 'Génère une liste en évaluant prog pour var de deb à fin.' },
  { nom: 'ADD', sujet: 'Listes', pile: '{ } { } → { }', description: 'Addition élément par élément de deux listes.' },

  // Chaînes
  { nom: '→STR', sujet: 'Chaînes', pile: 'obj → str', description: 'Convertit un objet en chaîne.' },
  { nom: 'STR→', sujet: 'Chaînes', pile: 'str → obj', description: 'Évalue une chaîne comme du RPL (parse).' },
  { nom: 'CHR', sujet: 'Chaînes', pile: 'n → str', description: 'Caractère de code n.' },
  { nom: 'NUM', sujet: 'Chaînes', pile: 'str → n', description: 'Code du premier caractère.' },
  { nom: '→TAG', sujet: 'Chaînes', pile: 'obj str → :str:obj', description: 'Étiquette un objet (tag).' },
  { nom: 'DTAG', sujet: 'Chaînes', pile: ':tag:obj → obj', description: 'Retire l’étiquette.' },

  // Matrices & vecteurs
  { nom: '→ARRY', sujet: 'Matrices & vecteurs', pile: 'x… { n m } → [[ ]]', description: 'Assemble des nombres en tableau.' },
  { nom: 'ARRY→', sujet: 'Matrices & vecteurs', pile: '[[ ]] → x… { n m }', description: 'Éclate un tableau sur la pile.' },
  { nom: 'CON', sujet: 'Matrices & vecteurs', pile: '{ n m } x → [[ ]]', description: 'Tableau constant rempli de x.' },
  { nom: 'IDN', sujet: 'Matrices & vecteurs', pile: 'n → [[ ]]', description: 'Matrice identité n×n.' },
  { nom: 'RDM', sujet: 'Matrices & vecteurs', pile: '[[ ]] { n m } → [[ ]]', description: 'Redimensionne un tableau.' },
  { nom: 'TRN', sujet: 'Matrices & vecteurs', pile: '[[ ]] → [[ ]]', description: 'Transposée (conjuguée).' },
  { nom: 'DET', sujet: 'Matrices & vecteurs', pile: '[[ ]] → x', description: 'Déterminant.' },
  { nom: 'CROSS', sujet: 'Matrices & vecteurs', pile: '[a] [b] → [a×b]', description: 'Produit vectoriel.' },
  { nom: 'DOT', sujet: 'Matrices & vecteurs', pile: '[a] [b] → x', description: 'Produit scalaire.' },
  { nom: 'RSD', sujet: 'Matrices & vecteurs', pile: 'B A X → résidu', description: 'Résidu B−AX (affinage de solution).' },
  { nom: 'RNRM', sujet: 'Matrices & vecteurs', pile: '[[ ]] → x', description: 'Norme de ligne (max des sommes de lignes).' },
  { nom: 'CNRM', sujet: 'Matrices & vecteurs', pile: '[[ ]] → x', description: 'Norme de colonne.' },
  { nom: 'V→', sujet: 'Matrices & vecteurs', pile: '[v] → x y (z)', description: 'Décompose un vecteur 2D/3D selon le mode.' },
  { nom: '→V2', sujet: 'Matrices & vecteurs', pile: 'x y → [v]', description: 'Assemble un vecteur 2D.' },
  { nom: '→V3', sujet: 'Matrices & vecteurs', pile: 'x y z → [v]', description: 'Assemble un vecteur 3D.' },

  // Graphismes & GROB
  { nom: '→GROB', sujet: 'Graphismes & GROB', pile: 'obj n → grob', description: 'Convertit un objet en GROB (n = taille de police 0–3).' },
  { nom: 'LCD→', sujet: 'Graphismes & GROB', pile: '→ grob', description: 'Capture l’écran dans un GROB 131×64.' },
  { nom: '→LCD', sujet: 'Graphismes & GROB', pile: 'grob →', description: 'Affiche un GROB directement à l’écran.' },
  { nom: 'BLANK', sujet: 'Graphismes & GROB', pile: '#l #h → grob', description: 'Crée un GROB vide de largeur et hauteur données.' },
  { nom: 'GOR', sujet: 'Graphismes & GROB', pile: 'g1 pos g2 → g', description: 'Superpose g2 sur g1 (OU logique des pixels).' },
  { nom: 'GXOR', sujet: 'Graphismes & GROB', pile: 'g1 pos g2 → g', description: 'Superpose en XOR (inversion, pratique pour les curseurs).' },
  { nom: 'PICT', sujet: 'Graphismes & GROB', description: 'Nom de l’écran graphique (utilisable avec STO, RCL, GOR…).' },
  { nom: 'PVIEW', sujet: 'Graphismes & GROB', pile: 'pos →', description: 'Affiche PICT à partir de la position donnée.' },
  { nom: 'PIXON', sujet: 'Graphismes & GROB', pile: '{ x y } →', description: 'Allume un pixel de PICT.' },
  { nom: 'PIXOFF', sujet: 'Graphismes & GROB', pile: '{ x y } →', description: 'Éteint un pixel de PICT.' },
  { nom: 'PIX?', sujet: 'Graphismes & GROB', pile: '{ x y } → 0/1', description: 'Teste un pixel de PICT.' },
  { nom: 'LINE', sujet: 'Graphismes & GROB', pile: 'p1 p2 →', description: 'Trace une ligne dans PICT.' },
  { nom: 'TLINE', sujet: 'Graphismes & GROB', pile: 'p1 p2 →', description: 'Ligne en mode inversion (toggle).' },
  { nom: 'BOX', sujet: 'Graphismes & GROB', pile: 'p1 p2 →', description: 'Trace un rectangle.' },
  { nom: 'ARC', sujet: 'Graphismes & GROB', pile: 'c r a1 a2 →', description: 'Trace un arc de cercle.' },
  { nom: 'TEXT', sujet: 'Graphismes & GROB', description: 'Bascule l’affichage sur l’écran pile (quitte le graphique).' },
  { nom: 'PX→C', sujet: 'Graphismes & GROB', pile: '{ #x #y } → (x,y)', description: 'Coordonnées pixel vers coordonnées utilisateur.' },
  { nom: 'C→PX', sujet: 'Graphismes & GROB', pile: '(x,y) → { #x #y }', description: 'Coordonnées utilisateur vers pixel.' },
  { nom: 'PDIM', sujet: 'Graphismes & GROB', pile: '#l #h →', description: 'Redimensionne PICT.' },
  { nom: 'ANIMATE', sujet: 'Graphismes & GROB', pile: 'grob… n → …', description: 'Anime une suite de GROBs.' },

  // Tracé de courbes
  { nom: 'STEQ', sujet: 'Tracé de courbes', pile: 'expr →', description: 'Stocke l’équation courante (EQ).' },
  { nom: 'RCEQ', sujet: 'Tracé de courbes', pile: '→ expr', description: 'Rappelle l’équation courante.' },
  { nom: 'DRAW', sujet: 'Tracé de courbes', description: 'Trace la courbe de EQ dans PICT.' },
  { nom: 'DRAX', sujet: 'Tracé de courbes', description: 'Trace les axes.' },
  { nom: 'ERASE', sujet: 'Tracé de courbes', description: 'Efface PICT.' },
  { nom: 'AUTO', sujet: 'Tracé de courbes', description: 'Ajuste automatiquement l’échelle verticale.' },
  { nom: 'XRNG', sujet: 'Tracé de courbes', pile: 'xmin xmax →', description: 'Fixe l’intervalle horizontal du tracé.' },
  { nom: 'YRNG', sujet: 'Tracé de courbes', pile: 'ymin ymax →', description: 'Fixe l’intervalle vertical.' },
  { nom: 'INDEP', sujet: 'Tracé de courbes', pile: 'nom →', description: 'Choisit la variable indépendante.' },
  { nom: 'DEPND', sujet: 'Tracé de courbes', pile: 'nom →', description: 'Choisit la variable dépendante.' },
  { nom: 'FUNCTION', sujet: 'Tracé de courbes', description: 'Mode de tracé « fonction » (aussi POLAR, PARAMETRIC, CONIC…).' },
  { nom: 'ROOT', sujet: 'Tracé de courbes', pile: 'expr nom x0 → x', description: 'Résout numériquement expr=0 près de x0.' },

  // Symbolique
  { nom: 'COLCT', sujet: 'Symbolique', pile: 'symb → symb', description: 'Regroupe les termes semblables.' },
  { nom: 'EXPAN', sujet: 'Symbolique', pile: 'symb → symb', description: 'Développe produits et puissances.' },
  { nom: 'ISOL', sujet: 'Symbolique', pile: 'symb nom → symb', description: 'Isole une variable dans une équation.' },
  { nom: 'QUAD', sujet: 'Symbolique', pile: 'symb nom → symb', description: 'Résout un polynôme du second degré.' },
  { nom: 'SHOW', sujet: 'Symbolique', pile: 'symb nom → symb', description: 'Ré-exprime en montrant la variable cachée.' },
  { nom: 'TAYLR', sujet: 'Symbolique', pile: 'symb nom n → symb', description: 'Développement de Taylor à l’ordre n.' },
  { nom: '∂', sujet: 'Symbolique', pile: 'symb nom → symb', description: 'Dérivée par rapport à une variable.' },
  { nom: '∫', sujet: 'Symbolique', pile: 'a b symb nom → x', description: 'Intégrale (numérique ou symbolique).' },
  { nom: '|', sujet: 'Symbolique', pile: 'symb { nom val } → symb', description: 'Substitution : évalue « où » nom = val.' },
  { nom: 'APPLY', sujet: 'Symbolique', pile: '{ args } nom → symb', description: 'Construit une expression fonction(args).' },
  { nom: 'QUOTE', sujet: 'Symbolique', pile: 'symb → symb', description: 'Empêche l’évaluation d’une expression.' },
  { nom: 'DEFINE', sujet: 'Symbolique', pile: 'nom=expr →', description: 'Crée une variable ou une fonction depuis une équation.' },
  { nom: 'ΣVX', sujet: 'Symbolique', description: 'Nom de la variable symbolique courante (VX, en général X).' },

  // Statistiques
  { nom: 'Σ+', sujet: 'Statistiques', pile: 'x / [x y…] →', description: 'Ajoute un point de données à ΣDAT.' },
  { nom: 'Σ-', sujet: 'Statistiques', pile: '→ x / [x y…]', description: 'Retire le dernier point de ΣDAT.' },
  { nom: 'CLΣ', sujet: 'Statistiques', description: 'Efface les données statistiques.' },
  { nom: 'STOΣ', sujet: 'Statistiques', pile: 'obj →', description: 'Stocke une matrice dans ΣDAT.' },
  { nom: 'NΣ', sujet: 'Statistiques', pile: '→ n', description: 'Nombre de points de données.' },
  { nom: 'MEAN', sujet: 'Statistiques', pile: '→ x', description: 'Moyenne des colonnes de ΣDAT.' },
  { nom: 'SDEV', sujet: 'Statistiques', pile: '→ x', description: 'Écart-type (échantillon).' },
  { nom: 'PSDEV', sujet: 'Statistiques', pile: '→ x', description: 'Écart-type (population).' },
  { nom: 'VAR', sujet: 'Statistiques', pile: '→ x', description: 'Variance.' },
  { nom: 'TOT', sujet: 'Statistiques', pile: '→ x', description: 'Somme des colonnes.' },
  { nom: 'MAXΣ', sujet: 'Statistiques', pile: '→ x', description: 'Maximum de chaque colonne.' },
  { nom: 'MINΣ', sujet: 'Statistiques', pile: '→ x', description: 'Minimum de chaque colonne.' },
  { nom: 'CORR', sujet: 'Statistiques', pile: '→ x', description: 'Coefficient de corrélation.' },
  { nom: 'COV', sujet: 'Statistiques', pile: '→ x', description: 'Covariance.' },
  { nom: 'LR', sujet: 'Statistiques', pile: '→ b m', description: 'Régression linéaire (ordonnée à l’origine et pente).' },
  { nom: 'PREDY', sujet: 'Statistiques', pile: 'x → y', description: 'Prédit y à partir de x selon la régression.' },
  { nom: 'PREDX', sujet: 'Statistiques', pile: 'y → x', description: 'Prédit x à partir de y.' },
  { nom: 'UTPN', sujet: 'Statistiques', pile: 'm v x → p', description: 'Probabilité de la queue supérieure (loi normale).' },

  // Unités
  { nom: '→UNIT', sujet: 'Unités', pile: 'x unité → x_unité', description: 'Attache une unité à un nombre.' },
  { nom: 'UBASE', sujet: 'Unités', pile: 'x_u → x_SI', description: 'Convertit en unités SI de base.' },
  { nom: 'UVAL', sujet: 'Unités', pile: 'x_u → x', description: 'Valeur numérique sans l’unité.' },
  { nom: 'CONVERT', sujet: 'Unités', pile: 'x_u1 1_u2 → x_u2', description: 'Convertit d’une unité vers une autre.' },
  { nom: 'UFACT', sujet: 'Unités', pile: 'x_u1 1_u2 → x_u2·u1/u2', description: 'Factorise une unité dans une autre.' },

  // Heure & date
  { nom: 'DATE', sujet: 'Heure & date', pile: '→ date', description: 'Date courante (JJ.MMAAAA ou MM.JJAAAA selon le mode).' },
  { nom: 'TIME', sujet: 'Heure & date', pile: '→ heure', description: 'Heure courante (HH.MMSS).' },
  { nom: 'TICKS', sujet: 'Heure & date', pile: '→ #n', description: 'Horloge système en tics de 1/8192 s (pour chronométrer).' },
  { nom: 'DATE+', sujet: 'Heure & date', pile: 'date n → date', description: 'Ajoute n jours à une date.' },
  { nom: 'DDAYS', sujet: 'Heure & date', pile: 'date1 date2 → n', description: 'Nombre de jours entre deux dates.' },
  { nom: '→HMS', sujet: 'Heure & date', pile: 'x → hms', description: 'Heures décimales vers HH.MMSS.' },
  { nom: 'HMS→', sujet: 'Heure & date', pile: 'hms → x', description: 'HH.MMSS vers heures décimales.' },
  { nom: 'HMS+', sujet: 'Heure & date', pile: 'hms hms → hms', description: 'Addition en heures-minutes-secondes.' },
  { nom: 'HMS-', sujet: 'Heure & date', pile: 'hms hms → hms', description: 'Soustraction en HMS.' },
  { nom: 'TSTR', sujet: 'Heure & date', pile: 'date heure → str', description: 'Date et heure formatées en chaîne.' },

  // Affichage & clavier
  { nom: 'DISP', sujet: 'Affichage & clavier', pile: 'obj n →', description: 'Affiche l’objet sur la ligne n (1–7).' },
  { nom: 'CLLCD', sujet: 'Affichage & clavier', description: 'Efface l’écran.' },
  { nom: 'FREEZE', sujet: 'Affichage & clavier', pile: 'n →', description: 'Gèle des zones d’écran (1=état, 2=pile, 4=menu, additionnables).' },
  { nom: 'MSGBOX', sujet: 'Affichage & clavier', pile: 'str →', description: 'Affiche un message dans une boîte de dialogue.' },
  { nom: 'PROMPT', sujet: 'Affichage & clavier', pile: 'str →', description: 'Affiche un message et suspend le programme.' },
  { nom: 'INPUT', sujet: 'Affichage & clavier', pile: 'str str → str', description: 'Saisie d’une valeur par l’utilisateur.' },
  { nom: 'INFORM', sujet: 'Affichage & clavier', pile: '… → … 0/1', description: 'Formulaire de saisie complet (boîte de dialogue).' },
  { nom: 'CHOOSE', sujet: 'Affichage & clavier', pile: 'str { } n → obj 1 / 0', description: 'Menu de choix dans une boîte.' },
  { nom: 'KEY', sujet: 'Affichage & clavier', pile: '→ 0 / n 1', description: 'Lit une touche sans attendre.' },
  { nom: 'BEEP', sujet: 'Affichage & clavier', pile: 'fréq durée →', description: 'Émet un bip (Hz, secondes).' },
  { nom: 'MENU', sujet: 'Affichage & clavier', pile: 'n / { } →', description: 'Affiche un menu (numéro ou menu personnalisé).' },
  { nom: 'TMENU', sujet: 'Affichage & clavier', pile: '{ } →', description: 'Menu temporaire (sans toucher CST).' },
  { nom: 'RCLMENU', sujet: 'Affichage & clavier', pile: '→ n', description: 'Numéro du menu courant.' },
  { nom: 'ASN', sujet: 'Affichage & clavier', pile: 'obj n →', description: 'Assigne un objet à une touche (clavier utilisateur).' },
  { nom: 'STOKEYS', sujet: 'Affichage & clavier', pile: '{ } →', description: 'Définit plusieurs touches utilisateur.' },
  { nom: 'DELKEYS', sujet: 'Affichage & clavier', pile: 'n / 0 →', description: 'Supprime des assignations de touches.' },
]
